### ISSUE TITLE
AttributeError: 'CutSet' object has no attribute 'find'

### ISSUE THREAD

**Issue by sankar-mukherjee** [lhotse-speech/lhotse#1024]
Traceback (most recent call last):
  File "/workspaces/vall-e/egs/libritts/bin/tokenizer.py", line 204, in <module>
    main()
  File "/workspaces/vall-e/egs/libritts/bin/tokenizer.py", line 146, in main
    cut_set = CutSet.from_manifests(
  File "/root/miniconda3/envs/valle/lib/python3.10/site-packages/lhotse/cut/set.py", line 317, in from_manifests
    return create_cut_set_eager(
  File "/root/miniconda3/envs/valle/lib/python3.10/site-packages/lhotse/cut/set.py", line 2937, in create_cut_set_eager
    supervisions.find(
AttributeError: 'CutSet' object has no attribute 'find'

**Comment by sankar-mukherjee** [comment]
I was using this repo to run valle. 
https://github.com/lifeiteng/vall-e

I am running libritts data. after downloading the data the error come when calling this line in the prepare.sh

https://github.com/lifeiteng/vall-e/blob/6d1e8e2c61b6ecee32552f96bc12a303eaef686c/egs/libritts/prepare.sh#L72

more specifically here

https://github.com/lifeiteng/vall-e/blob/6d1e8e2c61b6ecee32552f96bc12a303eaef686c/valle/bin/tokenizer.py#L146

fyi supervisions were set to eager mode 
https://github.com/lhotse-speech/lhotse/blob/7edc9aea48974b0f421bdd8ed3dfd221bdb265f8/lhotse/cut/set.py#L2916

**Comment by pzelasko** [comment]
Did you modify the code somehow? Can print the value of `m["supervisions"]` in this line https://github.com/lifeiteng/vall-e/blob/6d1e8e2c61b6ecee32552f96bc12a303eaef686c/valle/bin/tokenizer.py#L150?

**Comment by sankar-mukherjee** [comment]
```
m["supervisions"]
CutSet(len=0) [underlying data type: <class 'dict'>]
special variables
function variables
cuts:
{}
data:
{}
ids:
dict_keys([])
is_lazy:
False
mixed_cuts:
{}
multi_cuts:
{}
simple_cuts:
{}
speakers:
frozenset({})
_abc_impl:
<_abc._abc_data object at 0x7ff01fbfc980>
_is_protocol:
False
```

```
m["recordings"]
RecordingSet(len=33236)
special variables
function variables
data:
{'6454_107462_000020_000000': Recording(id='6454_1...orms=None), '6454_107462_000029_000005': Recording(id='6454_1...orms=None), '6454_107462_000014_000001': Recording(id='6454_1...orms=None), '6454_107462_000027_000001': Recording(id='6454_1...orms=None), '6454_107462_000024_000003': Recording(id='6454_1...orms=None), '6454_107462_000036_000000': Recording(id='6454_1...orms=None), '6454_107462_000005_000001': Recording(id='6454_1...orms=None), '6454_107462_000006_000000': Recording(id='6454_1...orms=None), '6454_107462_000023_000000': Recording(id='6454_1...orms=None), '6454_107462_000008_000000': Recording(id='6454_1...orms=None), '6454_107462_000005_000004': Recording(id='6454_1...orms=None), '6454_107462_000025_000001': Recording(id='6454_1...orms=None), '6454_107462_000014_000002': Recording(id='6454_1...orms=None), '6454_107462_000018_000000': Recording(id='6454_1...orms=None), ...}
ids:
dict_keys(['6454_107462_000020_000000', '6454_107462_000029_000005', '6454_107462_000014_000001', '6454_107462_000027_000001', '6454_107462_000024_000003', '6454_107462_000036_000000', '6454_107462_000005_000001', '6454_107462_000006_000000', '6454_107462_000023_000000', '6454_107462_000008_000000', '6454_107462_000005_000004', '6454_107462_000025_000001', '6454_107462_000014_000002', '6454_107462_000018_000000', '6454_107462_000017_000001', '6454_107462_000008_000001', '6454_107462_000008_000004', '6454_107462_000016_000001', '6454_107462_000022_000000', '6454_107462_000010_000001', '6454_107462_000019_000001', '6454_107462_000037_000000', '6454_107462_000006_000001', '6454_107462_000007_000000', '6454_107462_000024_000001', '6454_107462_000024_000000', '6454_107462_000031_000000', '6454_107462_000012_000000', '6454_107462_000023_000001', '6454_107462_000034_000000', '6454_107462_000024_000002', '6454_107462_000005_000003', '6454_107462_000011_000000', '6454_107462_000016_000000', '6454_107462_000010_000002'...
is_lazy:
False
recordings:
{'6454_107462_000020_000000': Recording(id='6454_1...orms=None), '6454_107462_000029_000005': Recording(id='6454_1...orms=None), '6454_107462_000014_000001': Recording(id='6454_1...orms=None), '6454_107462_000027_000001': Recording(id='6454_1...orms=None), '6454_107462_000024_000003': Recording(id='6454_1...orms=None), '6454_107462_000036_000000': Recording(id='6454_1...orms=None), '6454_107462_000005_000001': Recording(id='6454_1...orms=None), '6454_107462_000006_000000': Recording(id='6454_1...orms=None), '6454_107462_000023_000000': Recording(id='6454_1...orms=None), '6454_107462_000008_000000': Recording(id='6454_1...orms=None), '6454_107462_000005_000004': Recording(id='6454_1...orms=None), '6454_107462_000025_000001': Recording(id='6454_1...orms=None), '6454_107462_000014_000002': Recording(id='6454_1...orms=None), '6454_107462_000018_000000': Recording(id='6454_1...orms=None), ...}
_abc_impl:
<_abc._abc_data object at 0x7ff0b88c6200>
_is_protocol:
False
```

**Comment by pzelasko** [comment]
Looks like your supervision manifest got corrupted, it’s probably accidentally overwritten with an empty cut set. Try recreating your data. You can use `lhotse prepare libritts …` CLI and manually override the paths.

**Comment by sankar-mukherjee** [comment]
you are right indeed it was getting over written. Thank you for your help @pzelasko
