### ISSUE TITLE
AssertionError: Inconsistent number of samples in a MixedCut

### ISSUE THREAD

**Issue by PPGGG** [lhotse-speech/lhotse#1065]
When i tried to train zipformer with on-the-fly feature extraction, i first generated and validated the manifest file (`supervisions_train.jsonl.gz` and `recordings_train.jsonl.gz`. However, about four hours in the training process, i met the following error :

```
Traceback (most recent call last):
  File "pruned_transducer_stateless7_streaming/train.py", line 1505, in <module>
    main()
  File "pruned_transducer_stateless7_streaming/train.py", line 1496, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/icefall/egs/aidatatang_200zh/ASR/pruned_transducer_stateless7_streaming/train.py", line 1334, in run
    train_one_epoch(
  File "/home/icefall/egs/aidatatang_200zh/ASR/pruned_transducer_stateless7_streaming/train.py", line 986, in train_one_epoch
    for batch_idx, batch in enumerate(train_dl):
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/utils.py", line 760, in wrapper
    return fn(*args, **kwargs)
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/cut/mixed.py", line 1077, in load_audio
    assert audio.shape[1] == self.num_samples, (
AssertionError: Inconsistent number of samples in a MixedCut: please report this issue at https://github.com/lhotse-speech/lhotse/issues showing the cut below. MixedCut:
MixedCut(id='7d54c4fda50649e5a131078a6df121c0_1666878599262', tracks=[MixTrack(cut=MonoCut(id='7d54c4fda50649e5a131078a6df121c0_1666878599262', start=0.0, duration=9.9995625, channel=0, supervisions=[SupervisionSegment(id='7d54c4fda50649e5a131078a6df121c0_1666878599262', recording_id='7d54c4fda50649e5a131078a6df121c0_1666878599262', start=0.0, duration=9.9995625, channel=0, text='今天天气怎么样', language='Chinese', speaker='7d54c4fda50649e5a131078a6df121c0_1666878599262', gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='7d54c4fda50649e5a131078a6df121c0_1666878599262', sources=[AudioSource(type='file', channels=[0], source='/home/wav/7d54c4fda50649e5a131078a6df121c0_666878599262.wav')], sampling_rate=16000, num_samples=159993, duration=9.9995625, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=None), MixTrack(cut=MonoCut(id='03b5f9b0-1e7-4d07-836c-ef5307754a7b', start=0.0, duration=9.9995625, channel=0, supervisions=[], features=Features(type='kaldi-fbank', num_frames=1000, num_features=80, frame_shift=0.01, sampling_rate=16000, start=0.0, duration=10.0, storage_type='lilcom_chunky', storage_path='data/fbank/musan_feats/feats-4.lca', storage_key='220142648,44049,44714', recording_id='None', channels=0), recording=Recording(id='noise-free-sound-0352', sources=[AudioSource(type='file', channels=[0], source='/home/musan/noise/free-sound/noise-free-sound-0352.wav')], sampling_rate=16000, num_samples=160000, duration=10.0, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr=17.364712141640126)], transforms=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = self.dataset[possibly_batched_index]
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/dataset/speech_recognition.py", line 116, in __getitem__
    input_tpl = self.input_strategy(cuts)
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/dataset/input_strategies.py", line 356, in __call__
    audios, cuts = read_audio_from_cuts(
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/dataset/collation.py", line 465, in read_audio_from_cuts
    for idx, (cut, maybe_audio) in enumerate(
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/dataset/collation.py", line 502, in _read_audio
    audio = cut.load_audio()
  File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/lhotse/utils.py", line 762, in wrapper
    raise type(e)(                                                                      
```

**Comment by pzelasko** [comment]
Please re-try with the latest `lhotse` (install via `pip uninstall lhotse && pip install git+https://github.com/lhotse-speech/lhotse`, I will soon release a new version with a fix for this.

**Comment by PPGGG** [comment]
> Please re-try with the latest `lhotse` (install via `pip uninstall lhotse && pip install git+https://github.com/lhotse-speech/lhotse`, I will soon release a new version with a fix for this.

Thanks a lot.
