### ISSUE TITLE
Compatible issue w. `export TORCHAUDIO_USE_BACKEND_DISPATCHER=1`

### ISSUE THREAD

**Issue by JinZr** [lhotse-speech/lhotse#1158]
I tried to enable the `TorchaudioFFMPEGBackend` by setting `TORCHAUDIO_USE_BACKEND_DISPATCHER=1`. 

This modification causes this error when extracting feature for wenetspeech.

```
Traceback (most recent call last):                                                                                                                       
  File "/star-home/jinzengrui/dev/icefall/egs/wenetspeech/ASR/./local/compute_fbank_wenetspeech_splits.py", line 178, in <module>                        
    main()                                                                                                                                               
  File "/star-home/jinzengrui/dev/icefall/egs/wenetspeech/ASR/./local/compute_fbank_wenetspeech_splits.py", line 174, in main                            
    compute_fbank_wenetspeech_splits(args)                                                                                                               
  File "/star-home/jinzengrui/dev/icefall/egs/wenetspeech/ASR/./local/compute_fbank_wenetspeech_splits.py", line 137, in compute_fbank_wenetspeech_split$
    cut_set = cut_set.compute_and_store_features_batch(                                                                                                  
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                  
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/cut/set.py", $
ine 2273, in compute_and_store_features_batch                                                                                                            
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__                
    data = self._next_data()                                                                                                                             
           ^^^^^^^^^^^^^^^^^                                                                                                                             
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data             
    return self._process_data(data)                                                                                                                      
           ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                      
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data          
    data.reraise()                                                                                                                                       
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/utils.py", lin
e 804, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/audio.py", lin
e 654, in load_audio
    audio = assert_and_maybe_fix_num_samples(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/audio.py", lin
e 2235, in assert_and_maybe_fix_num_samples
    raise ValueError(
ValueError: The number of declared samples in the recording diverged from the one obtained when loading audio (offset=99.36, duration=3.64). This could b
e internal Lhotse's error or a faulty transform implementation. Please report this issue in Lhotse and show the following: diff=-116480, audio.shape=(1,
174720), recording=Recording(id='Y0000008383_LSBx7EWal68', sources=[AudioSource(type='file', channels=[0], source='/star-home/jinzengrui/dev/icefall/egs/
wenetspeech/ASR/download/WenetSpeech/audio/train/youtube/B00032/Y0000008383_LSBx7EWal68.opus')], sampling_rate=16000, num_samples=43658400, duration=2728
.65, channel_ids=[0], transforms=None)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/utils.py", lin
e 804, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/cut/mono.py",
line 76, in load_audio
    return self.recording.load_audio(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/utils.py", lin
e 806, in wrapper
    raise type(e)(
ValueError: The number of declared samples in the recording diverged from the one obtained when loading audio (offset=99.36, duration=3.64). This could b
e internal Lhotse's error or a faulty transform implementation. Please report this issue in Lhotse and show the following: diff=-116480, audio.shape=(1,
174720), recording=Recording(id='Y0000008383_LSBx7EWal68', sources=[AudioSource(type='file', channels=[0], source='/star-home/jinzengrui/dev/icefall/egs/
wenetspeech/ASR/download/WenetSpeech/audio/train/youtube/B00032/Y0000008383_LSBx7EWal68.opus')], sampling_rate=16000, num_samples=43658400, duration=2728
.65, channel_ids=[0], transforms=None)
[extra info] When calling: Recording.load_audio(args=(Recording(id='Y0000008383_LSBx7EWal68', sources=[AudioSource(type='file', channels=[0], source='/st
ar-home/jinzengrui/dev/icefall/egs/wenetspeech/ASR/download/WenetSpeech/audio/train/youtube/B00032/Y0000008383_LSBx7EWal68.opus')], sampling_rate=16000,
num_samples=43658400, duration=2728.65, channel_ids=[0], transforms=None),) kwargs={'channels': 0, 'offset': 99.36, 'duration': 3.64})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 53, in fetch
    data = self.dataset[possibly_batched_index]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/dataset/unsupe
rvised.py", line 79, in __getitem__
    remain_audios.append(c.load_audio())
                         ^^^^^^^^^^^^^^
  File "/star-home/jinzengrui/lib/miniconda3/envs/dev/lib/python3.11/site-packages/lhotse-1.16.0.dev0+git.1db4d97a.dirty-py3.11.egg/lhotse/utils.py", lin
e 806, in wrapper
    raise type(e)(
ValueError: The number of declared samples in the recording diverged from the one obtained when loading audio (offset=99.36, duration=3.64). This could b
e internal Lhotse's error or a faulty transform implementation. Please report this issue in Lhotse and show the following: diff=-116480, audio.shape=(1,
174720), recording=Recording(id='Y0000008383_LSBx7EWal68', sources=[AudioSource(type='file', channels=[0], source='/star-home/jinzengrui/dev/icefall/egs/
wenetspeech/ASR/download/WenetSpeech/audio/train/youtube/B00032/Y0000008383_LSBx7EWal68.opus')], sampling_rate=16000, num_samples=43658400, duration=2728
.65, channel_ids=[0], transforms=None)
[extra info] When calling: Recording.load_audio(args=(Recording(id='Y0000008383_LSBx7EWal68', sources=[AudioSource(type='file', channels=[0], source='/st
ar-home/jinzengrui/dev/icefall/egs/wenetspeech/ASR/download/WenetSpeech/audio/train/youtube/B00032/Y0000008383_LSBx7EWal68.opus')], sampling_rate=16000,
num_samples=43658400, duration=2728.65, channel_ids=[0], transforms=None),) kwargs={'channels': 0, 'offset': 99.36, 'duration': 3.64})
[extra info] When calling: MonoCut.load_audio(args=(MonoCut(id='Y0000008383_LSBx7EWal68_S00000', start=99.36, duration=3.64, channel=0, supervisions=[Sup
ervisionSegment(id='Y0000008383_LSBx7EWal68_S00000', recording_id='Y0000008383_LSBx7EWal68', start=0.0, duration=3.64, channel=0, text='________________
__', language='Chinese', speaker=None, gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='Y0000008383_LSBx7EWal68', sourc
es=[AudioSource(type='file', channels=[0], source='/star-home/jinzengrui/dev/icefall/egs/wenetspeech/ASR/download/WenetSpeech/audio/train/youtube/B00032/
Y0000008383_LSBx7EWal68.opus')], sampling_rate=16000, num_samples=43658400, duration=2728.65, channel_ids=[0], transforms=None), custom=None),) kwargs={}
)
```

**Comment by JinZr** [comment]
Dear Piotr,

Thanks, forcing lhotse to use a certain backend works for me.


Best
