### ISSUE TITLE
404 not found error in `lhotse download ami --mic mdm ./` 

### ISSUE THREAD

**Issue by JinZr** [lhotse-speech/lhotse#1177]
After download certain number of utterances the command ran into this error. 
```
2023-10-08 22:25:59,639 INFO [utils.py:510] Server does not support range requests - attempting downloading from scratch████████████████████████████████████████████████████████████████████████████████ | 56.6M/57.0M [00:37<00:00, 2.10MB/s]
wav_db/IB4001/audio/IB4001.Array2-04.wav: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 57.0M/57.0M [00:36<00:00, 1.56MB/s]
Downloading AMI meetings: 76it [22:12:58, 1052.35s/it]██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 56.8M/57.0M [00:36<00:00, 1.53MB/s]
Traceback (most recent call last):
  File "/Users/zengruijin/miniconda3/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/lhotse/bin/modes/recipes/ami.py", line 122, in ami
    download_ami(
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/lhotse/recipes/ami.py", line 254, in download_ami
    download_audio(target_dir, force_download, url, mic)
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/lhotse/recipes/ami.py", line 210, in download_audio
    resumable_download(
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/lhotse/utils.py", line 515, in resumable_download
    raise e
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/lhotse/utils.py", line 500, in resumable_download
    _download(req, file_size)
  File "/Users/zengruijin/miniconda3/lib/python3.10/site-packages/lhotse/utils.py", line 482, in _download
    with urllib.request.urlopen(rq) as response:
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/zengruijin/miniconda3/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by pzelasko** [comment]
Maybe they removed some specific file from the server? Could you try to find out which file failed to download? CC @desh2608 did you see a similar error with AMI?

**Comment by desh2608** [comment]
@JinZr Can you check if you the corresponding file is available here: https://groups.inf.ed.ac.uk/ami/AMICorpusMirror/amicorpus/ (this is where we download the data from).

**Comment by JinZr** [comment]
Dear Desh and Piotr,


it looks like the issue is related to this dir:
https://groups.inf.ed.ac.uk/ami/AMICorpusMirror/amicorpus/IB4001/audio/

Array2 has only channel 1-4, channel 5-8 are not presented in the dir.


Best
Jin
