### ISSUE TITLE
Cannot load features for recording xxx starting from ... The available range is (..., ...)

### ISSUE THREAD

**Issue by trunglebka** [lhotse-speech/lhotse#1209]
I have encountered an error when training icefall at this line: https://github.com/k2-fsa/icefall/blob/231bbcd2b638826a94cf019fa31ae8683d3552ee/egs/gigaspeech/ASR/zipformer/train.py#L1299

Error log:
```
Minor icefall changes not related to lhotse that inappropriate to share
...
...
...
    batch = train_dl.dataset[cuts]
            ~~~~~~~~~~~~~~~~^^^^^^
  File "/opt/anaconda3/envs/k2/lib/python3.11/site-packages/lhotse/dataset/speech_recognition.py", line 116, in __getitem__
    input_tpl = self.input_strategy(cuts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/k2/lib/python3.11/site-packages/lhotse/dataset/input_strategies.py", line 120, in __call__
    return collate_features(
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/k2/lib/python3.11/site-packages/lhotse/dataset/collation.py", line 139, in collate_features
    features[idx] = _read_features(cut)
                    ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/k2/lib/python3.11/site-packages/lhotse/dataset/collation.py", line 613, in _read_features
    return torch.from_numpy(cut.load_features())
                            ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/k2/lib/python3.11/site-packages/lhotse/utils.py", line 837, in wrapper
    raise type(e)(
ValueError: Cannot load features for recording PART3_SeparateIVR_00862828 starting from 1343.5749375s. The available range is (1343.5749659863945, 1345.0750113378685) seconds.
[extra info] When calling: MonoCut.load_features(args=(MonoCut(id='PART3_SeparateIVR_00862828-463', start=1343.5749375, duration=1.5000625, channel=0, supervisions=[SupervisionSegment(id='PART3_SeparateIVR_00862828-463', recording_id='PAR
T3_SeparateIVR_00862828', start=0.0, duration=1.5, channel=0, text='YA', language='Singaporean English', speaker='PART3_SeparateIVR_00862828', gender=None, custom={'origin': 'nsc'}, alignment=None)], features=Features(type='kaldifeat-fban
k', num_frames=150, num_features=80, frame_shift=0.01, sampling_rate=16000, start=1343.5749659863945, duration=1.500045351473923, storage_type='lilcom_chunky', storage_path='data/nsc/fbank/nsc_feats_TRAIN.lca', storage_key='72195728247,14
325', recording_id='PART3_SeparateIVR_00862828', channels=0), recording=Recording(id='PART3_SeparateIVR_00862828', sources=[AudioSource(type='file', channels=[0], source='
/workspace/github/icefall/egs/combined_dataset/ASR/down
load/nsc/IMDA - National Speech Corpus/PART3/Audio Separate IVR/conf_2735_2735/00862828.wav')], sampling_rate=16000, num_samples=136278348, duration=8517.39675, channel_ids=[0], transforms=[{'name': 'Resample', 'kwargs': {'source_sampling
_rate': 11025, 'target_sampling_rate': 16000}}]), custom=None),) kwargs={})
[extra info] When calling: MixedCut.load_features(args=(MixedCut(id='ce9e1a11-fcbb-4e59-fbdd-cf7c9c96e9ec', tracks=[MixTrack(cut=MonoCut(id='PART3_SeparateIVR_00862828-463', start=1343.5749375, duration=1.5000625, channel=0, supervisions=
[SupervisionSegment(id='PART3_SeparateIVR_00862828-463', recording_id='PART3_SeparateIVR_00862828', start=0.0, duration=1.5, channel=0, text='YA', language='Singaporean English', speaker='PART3_SeparateIVR_00862828', gender=None, custom={
'origin': 'nsc'}, alignment=None)], features=Features(type='kaldifeat-fbank', num_frames=150, num_features=80, frame_shift=0.01, sampling_rate=16000, start=1343.5749659863945, duration=1.500045351473923, storage_type='lilcom_chunky', stor
age_path='data/nsc/fbank/nsc_feats_TRAIN.lca', storage_key='72195728247,14325', recording_id='PART3_SeparateIVR_00862828', channels=0), recording=Recording(id='PART3_SeparateIVR_00862828', sources=[AudioSource(type='file', channels=[0], s
ource='/workspace/github/icefall/egs/combined_dataset/ASR/download/nsc/IMDA - National Speech Corpus/PART3/Audio Separate IVR/conf_2735_2735/00862828.wav')], sampling_rate=16000, num_samples=136278348, duration=8517.39675, cha
nnel_ids=[0], transforms=[{'name': 'Resample', 'kwargs': {'source_sampling_rate': 11025, 'target_sampling_rate': 16000}}]), custom=None), type='MonoCut', offset=0.0, snr=None), MixTrack(cut=MonoCut(id='38503f73-6103-4af1-821b-8e5db58275b4
', start=390.0, duration=1.777375, channel=0, supervisions=[], features=Features(type='kaldi-fbank', num_frames=1000, num_features=80, frame_shift=0.01, sampling_rate=16000, start=390.0, duration=10.0, storage_type='lilcom_chunky', storag
e_path='data/fbank/musan_feats/feats-14.lca', storage_key='95084842,45096,46556', recording_id='None', channels=0), recording=Recording(id='speech-librivox-0036', sources=[AudioSource(type='file', channels=[0], source='/worksp
ace/github/icefall/egs/gigaspeech/ASR/download/musan/speech/librivox/speech-librivox-0036.wav')], sampling_rate=16000, num_samples=8434416, duration=527.151, channel_ids=[0], transforms=None), custom=None), type='MonoCut', offset=0.0, snr
=19.429097143350546), MixTrack(cut=PaddingCut(id='4d71c366-b41b-3143-8b10-550cd5704f32', duration=0.002625, sampling_rate=16000, feat_value=-23.025850929940457, num_frames=0, num_features=80, frame_shift=0.01, num_samples=42, video=None,
custom=None), type='PaddingCut', offset=1.777375, snr=None)], transforms=None),) kwargs={})
```

But it is weird that I can load the cut's feature with this code:
```
for c in cuts:
    print(c.id)
    if c.id == "PART3_SeparateIVR_00862828-463":
        feat = c.load_features()
        print(feat)
        break
```
Output of the code:
```
PART3_SeparateIVR_00862473-1691
210020267
208590368
230571579
PART3_SeparateIVR_00862828-463
[[-14.        -13.4375    -10.506836  ... -14.074113  -15.056743
  -14.684069 ]
 [-13.390625  -14.803467  -10.977406  ... -15.085524  -15.238966
  -15.674183 ]
 [-15.036011  -14.23101   -10.849762  ... -14.697529  -15.278957
  -15.24968  ]
 ...
 [-13.80121   -13.084278  -12.50919   ... -14.17049   -15.785528
  -15.228611 ]
 [-14.505888  -14.275627  -12.99749   ... -14.095924  -15.829395
  -15.072769 ]
 [-14.767561  -12.658012  -11.337238  ... -13.239546  -14.623505
  -14.5573845]]
```
Please help.

**Comment by desh2608** [comment]
Did you run `fix_manifests` on the manifests before creating the cuts?

**Comment by trunglebka** [comment]
@desh2608 No, I didn't run it. Just run [validate_manifest.py](https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/local/validate_manifest.py)

**Comment by desh2608** [comment]
Can you apply that (you can import it from `lhotse.qa`) and try again?

**Comment by trunglebka** [comment]
@desh2608 I tried fix_manifests, but it still happens.

**Comment by pzelasko** [comment]
Just to clarify, did you re-compute the features after applying `fix_manifests`? The issue here seems to be that somehow the cut start time does not correspond to features start time, and cut/feature duration is different than the supervision duration. I'm not sure how this might have happened. If all else fails and you don't want to recompute anything because of the size of the data, you can manually override `cut.start = cut.features.start` and `cut.duration = cut.features.duration` (maybe with some assertion that the difference is not greater than e.g. 0.5 seconds), which should be OK.

**Comment by trunglebka** [comment]
Here is the code that I used to prepare the data.
Not sure if  I am using `fix_manifests` correctly, please take a look.
https://gist.github.com/trunglebka/725ec0a8257b9369ac9f9a52d9a862b3#file-preprocess_nsc-py-L127

**Comment by pzelasko** [comment]
I think your code looks correct. I suggest to try manually fixing cut/supervision start/duration to match those of the attached features, e.g.:

```python
def adjust_timestamps(cut):
    cut.supervisions[0].start = cut.features.start
    cut.supervisions[0].duration = cut.features.duration
    cut.start = cut.features.start
    cut.duration = cut.features.duration
    return cut

cuts = cuts.map(adjust_timestamps)
```

And let us know if it helped. You might be running into some edge case related to the combination of non-trivial resampling (11.025kHz -> 16kHz) and time quantization into frames due to feature extraction.

**Comment by trunglebka** [comment]
@pzelasko 
Using your suggestion, I encountered this error:
```
  File "/opt/anaconda3/envs/k2/lib/python3.11/site-packages/lhotse/dataset/speech_recognition.py", line 99, in __getitem__
    validate_for_asr(cuts)
  File "/opt/anaconda3/envs/k2/lib/python3.11/site-packages/lhotse/dataset/speech_recognition.py", line 218, in validate_for_asr
    assert supervision.end <= cut.duration + tol, (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Supervisions ending after the cut are not supported for ASR (sup id: PART5_Debate_app_4077_6154_phnd_deb-3-8, cut id: PART5_Debate_app_4077_6154_phnd_deb-3-8)
```
Here is the cut:
```
{"id": "PART5_Debate_app_4077_6154_phnd_deb-3-8", "start": 58.16, "duration": 18.86, "channel": 0, "supervisions": [{"id": "PART5_Debate_app_4077_6154_phnd_deb-3-8", "recording_id": "PART5_Debate_app_4077_6154_phnd_deb-3", "start": 0.0, "duration": 18.86, "channel": 0, "text": "I I THINK THAT YOU KNOW THAT BEING AT HOME ALSO ALLOW YOU TO BE COMFORTABLE IN YOUR OWN SURROUNDING IN YOUR OWN ENVIRONMENT AND YOU ARE ABLE TO DO THINGS AT YOUR OWN PACE IN A MANNER THAT IS COMFORTABLE TO YOU AND WE ARE NOT SUBJECTED TO ANY PEER PRESSURE", "language": "Singaporean English", "speaker": "PART5_Debate_app_4077_6154_phnd_deb-3", "custom": {"origin": "nsc"}}], "features": {"type": "kaldifeat-fbank", "num_frames": 1886, "num_features": 80, "frame_shift": 0.01, "sampling_rate": 16000, "start": 58.16, "duration": 18.86, "storage_type": "lilcom_chunky", "storage_path": "data/nsc/fbank/nsc_feats_TRAIN.lca", "storage_key": "92800616774,46428,46061,46850,36727", "recording_id": "PART5_Debate_app_4077_6154_phnd_deb-3", "channels": 0}, "recording": {"id": "PART5_Debate_app_4077_6154_phnd_deb-3", "sources": [{"type": "file", "channels": [0], "source": "/workspace/github/icefall/egs/combined_dataset/ASR/download/nsc/IMDA - National Speech Corpus - Additional/IMDA - National Speech Corpus (Additional)/PART5/Debate Audio/4077/6154/app_4077_6154_phnd_deb-3.wav"}], "sampling_rate": 16000, "num_samples": 19686615, "duration": 1230.4134375, "channel_ids": [0]}, "type": "MonoCut"}
```

**Comment by trunglebka** [comment]
The above error likely due to supervision start is relative to cut start, but if I set `cut.supervisions[0].start = 0` the old error occurred:
```
ValueError: Cannot load features for recording PART3_SeparateIVR_00862275 starting from 1002.514s. The available range is (1002.5140136054422, 1003.5390476190477) seconds.
[extra info] When calling: MonoCut.load_features(args=(MonoCut(id='PART3_SeparateIVR_00862275-418', start=1002.514, duration=1.0250625, channel=0, supervisions=[SupervisionSegment(id='PART3_SeparateIVR_00862275-418', recording_id='PART3_S
eparateIVR_00862275', start=0.0, duration=1.025034013605442, channel=0, text='GOT EYES', language='Singaporean English', speaker='PART3_SeparateIVR_00862275', gender=None, custom={'origin': 'nsc'}, alignment=None)], features=Features(type
='kaldifeat-fbank', num_frames=103, num_features=80, frame_shift=0.01, sampling_rate=16000, start=1002.5140136054422, duration=1.025034013605442, storage_type='lilcom_chunky', storage_path='data/nsc/fbank/nsc_feats_TRAIN.lca', storage_key
='81946054677,9458', recording_id='PART3_SeparateIVR_00862275', channels=0), recording=Recording(id='PART3_SeparateIVR_00862275', sources=[AudioSource(type='file', channels=[0], source='/workspace/github/icefall/egs/combined_d
ataset/ASR/download/nsc/IMDA - National Speech Corpus/PART3/Audio Separate IVR/conf_2502_2502/00862275.wav')], sampling_rate=16000, num_samples=116205437, duration=7262.8398125, channel_ids=[0], transforms=[{'name': 'Resample', 'kwargs':
{'source_sampling_rate': 11025, 'target_sampling_rate': 16000}}]), custom=None),) kwargs={})
```
the weird thing is cut.start likely being rounded to 3 digits?

**Comment by pzelasko** [comment]
> @pzelasko Using your suggestion, I encountered this error:

Are you 100% sure you got the right cut/cutset? I copy-pasted and ran it, it seems to work ok... see

```python
cut = MonoCut.from_dict(...)
supervision = cut.supervisions[0]
print(supervision.end <= cut.duration + 1e-3)  # True
```

**Comment by trunglebka** [comment]
@pzelasko I believe it's the correct cutset, but I'm not entirely sure because I'm not proficient enough with Lhotse.
Regarding to the error `AssertionError: Supervisions ending after the cut are not supported for ASR` I think it is reasonable due to this [note](https://lhotse.readthedocs.io/en/latest/cuts.html#:~:text=All%20Cut%20classes%20assume%20that%20the%20SupervisionSegment%20time%20boundaries%20are%20relative%20to%20the%20beginning%20of%20the%20cut) , considering that the record contains multiple supervisions.
I exported the cuts to: [nsc_cuts_part3_00862275.wav.jsonl.gz](https://github.com/lhotse-speech/lhotse/files/13447088/nsc_cuts_part3_00862275.wav.jsonl.gz)
Using this code to verify its correctness, I'm still encountering the same error:
```
from lhotse import CutSet
from lhotse.cut import MonoCut
from lhotse.dataset.speech_recognition import (
    validate_for_asr,
)


def adjust_timestamps(cut: MonoCut):
    cut.supervisions[0].start = cut.features.start
    cut.supervisions[0].duration = cut.features.duration
    cut.start = cut.features.start
    cut.duration = cut.features.duration
    return cut


cuts = CutSet.from_file(
    "/home/chicky/Downloads/nsc-exp/nsc_cuts_part3_00862275.wav.jsonl"
)
cuts = cuts.map(adjust_timestamps)
validate_for_asr(cuts=cuts)

```
Above code's error:

```
Traceback (most recent call last):
  File "/home/chicky/workspace/lhotse-exp/cuts_exp.py", line 20, in <module>
    validate_for_asr(cuts=cuts)
  File "/home/trungle/opt/anaconda3/envs/k2/lib/python3.10/site-packages/lhotse/dataset/speech_recognition.py", line 218, in validate_for_asr
    assert supervision.end <= cut.duration + tol, (
AssertionError: Supervisions ending after the cut are not supported for ASR (sup id: PART3_SeparateIVR_00862275-294, cut id: PART3_SeparateIVR_00862275-294)
```
Sorry for the late response, I had to be off work for a while

**Comment by desh2608** [comment]
BTW you should use `trim_to_supervisions()` with the option `keep_overlapping=False` to ensure that all cuts have exactly one supervision and they are truncated as per the supervision's boundaries.

**Comment by trunglebka** [comment]
@desh2608 
The dataset was be prepared with default [trim_to_supervisions](https://gist.github.com/trunglebka/725ec0a8257b9369ac9f9a52d9a862b3#file-preprocess_nsc-py-L136) (keep_overlapping=True copied from gigaspeech recipe)
Preparing process take time and I encountered many problems with nsc dataset so in icefall's training code I'm filtering it like this:
![image](https://github.com/lhotse-speech/lhotse/assets/16150250/c6002119-4f48-4ae1-8b11-aee31bb6465e)

I'm not sure if it can be a "correct" subset of your suggestion's output.

**Comment by pzelasko** [comment]
I'll try to look into it later this week.

**Comment by LoganLiu66** [comment]
I have encountered the same problem on libriheavy dataset, and solve it by  adjust 
`cut["features"]["start"] = round(cut["features"]["start"], 2)`
