### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by Airgods** [lhotse-speech/lhotse#1389]
不知道为什么当我在使用wenetspeech下使用lhotse时做data prepare ，报了如下错误，思考了很久，并不知大该如何做才能解决？
2024-08-28 08:56:47 (prepare.sh:178:main) Stage 13: Combine features for L
Traceback (most recent call last):
  File "/data1/llm/anaconda3/envs/icefall/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/data1/llm/anaconda3/envs/icefall/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data1/llm/anaconda3/envs/icefall/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data1/llm/anaconda3/envs/icefall/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data1/llm/anaconda3/envs/icefall/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data1/llm/anaconda3/envs/icefall/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data1/llm/anaconda3/envs/icefall/lib/python3.8/site-packages/lhotse/bin/modes/manipulation.py", line 275, in combine
    data_set = combine_manifests(*[load_manifest_lazy_or_eager(m) for m in manifests])
  File "/data1/llm/anaconda3/envs/icefall/lib/python3.8/site-packages/lhotse/manipulation.py", line 30, in combine
    return reduce(add, manifests)
  File "/data1/llm/anaconda3/envs/icefall/lib/python3.8/site-packages/lhotse/lazy.py", line 174, in __add__
    return cls(LazyIteratorChain(self.data, other.data))
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by Airgods** [comment]
这是我的ltose的版本：lhotse-1.27.0.dev0+git.66b95ba.clean

**Comment by pzelasko** [comment]
Possibly one of the manifest paths is corrupted or doesn’t exist?

**Comment by Airgods** [comment]
> Possibly one of the manifest paths is corrupted or doesn’t exist?
请问这个该如何排查呢？我使用的是prepare.sh这个脚本，并没有做任何修改

**Comment by csukuangfj** [comment]
pdb 单步调试 @Airgods

**Comment by Airgods** [comment]
> pdb 单步调试 @Airgods

请问这个以prepare.sh文件启动，随后报错的是环境中配置lthose包，这个如何做到gdb单步调试呢

**Comment by csukuangfj** [comment]
请学习一下什么是pdb

重复一下，是pdb，不是gdb


你自己去看脚本，看跑的是哪个Python代码，传的什么参数
