### ISSUE TITLE
spgi duration interprocess crash fix 

### ISSUE THREAD

**Issue by pclpp** [lhotse-speech/lhotse#1391]
update lhotse/recipes/spgispeech.py with following replacement 

def audio_read_worker(p: Path) -> Recording:
            r = Recording.from_file(p, recording_id=f"{p.parent.stem}_{p.stem}")
            return r

        with RecordingSet.open_writer(
            output_dir / f"spgispeech_recordings_{part}.jsonl.gz"
        ) as rec_writer:
            for recording in tqdm(
                parallel_map(
                    audio_read_worker,
                    (audio_dir / part).rglob("*.wav"),
                    num_jobs=num_jobs,
                ),
                desc="Processing SPGISpeech recordings",
            ):
                durations[recording.id] = recording.duration
                rec_writer.write(recording)

fix the following problem: 

Processing SPGISpeech subset: train
Processing SPGISpeech recordings: 1966109it [2:40:35, 204.05it/s] 
Processing utterances: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/pcl/miniconda3/envs/huggingface/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/home/pcl/miniconda3/envs/huggingface/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/pcl/miniconda3/envs/huggingface/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/pcl/miniconda3/envs/huggingface/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pcl/miniconda3/envs/huggingface/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pcl/miniconda3/envs/huggingface/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pcl/miniconda3/envs/huggingface/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/huayun/miniconda3/envs/huggingface/lib/python3.9/site-packages/lhotse/bin/modes/recipes/spgispeech.py", line 30, in spgispeech
    prepare_spgispeech(
  File "/home/pcl/miniconda3/envs/huggingface/lib/python3.9/site-packages/lhotse/recipes/spgispeech.py", line 160, in prepare_spgispeech
    duration=durations[recording_id],
KeyError: '07a785e9237c389c1354bb60abca42d5_1'

**Comment by pzelasko** [comment]
Resolved via #1390
