### ISSUE TITLE
Rounding problem in Validation check for file qa.py In Lhotse

### ISSUE THREAD

**Issue by manu51188** [lhotse-speech/lhotse#201]
Hi Team,

I am currently working with CSJ corpus to extract features using Lhotse. There is one small issue which looks like this : 

```
Traceback (most recent call last):
  File "ctc_train.py", line 401, in <module>
    main()
  File "ctc_train.py", line 275, in main
    train = K2SpeechRecognitionDataset(cuts_train)
  File "/home/sysadmin/miniconda3/lib/python3.8/site-packages/lhotse/dataset/speech_recognition.py", line 69, in __init__
    self._validate()
  File "/home/sysadmin/miniconda3/lib/python3.8/site-packages/lhotse/dataset/speech_recognition.py", line 119, in _validate
    validate(self.cuts)
  File "/home/sysadmin/miniconda3/lib/python3.8/site-packages/lhotse/qa.py", line 34, in validate
    valid(obj, read_data=read_data)
  File "/home/sysadmin/miniconda3/lib/python3.8/site-packages/lhotse/qa.py", line 233, in validate_cut_set
    validate_cut(c, read_data=read_data)
  File "/home/sysadmin/miniconda3/lib/python3.8/site-packages/lhotse/qa.py", line 175, in validate_cut
    validate_recording(c.recording)
  File "/home/sysadmin/miniconda3/lib/python3.8/site-packages/lhotse/qa.py", line 91, in validate_recording
    assert isclose(expected_duration, r.duration), \
AssertionError: Recording A01M0632: mismatched declared duration (721.0584) with num_samples / sampling_rate (721.058375).
```

This is an assertion error for one of the file " A01M0632" in which above mismatch is due to rounding. The recorded duration is rounded to 4 decimal points , while expected duration is of 6 decimal points and final assertion error is raised. I can solve it by rounding the expected duration to 4 decimal points. There are two questions on which I need your help .

 1. Is doing rounding will not affect the rest of my training ?
 2. Can we look for more optimum solution for doing the above validation, so that in future it we can be take efficiently.

Regards,
Mohit

**Comment by pzelasko** [comment]
It seems like something weird happened when you created the recording manifests; if you multiply both values by CSJ's sampling rate (16000), it is `declared duration * sampling_rate = 11536934.4` and `actual_num_samples = 11536934`. Looks like you should adjust the manifest to reflect the actual duration. In any case, this is a very strict check; being off by one sample likely won't change affect your training.

**Comment by manu51188** [comment]
Hi @pzelasko ,

Thanks very much for the reply. I will check again how recording manifest  is created.

Regards,
Mohit

**Comment by pzelasko** [comment]
I understand that you were able to fix the issue - can we close this? Also do you think it would be possible for you to contribute the CSJ data prep recipe to Lhotse?

**Comment by manu51188** [comment]
Hi,

Yes sure. I can definitely contribute to the CSJ data preparation receipe to Lhotse. 
Just need to confirm with the team.

Thanks for all the support.

**Comment by pzelasko** [comment]
Looking forward to it!
