### ISSUE TITLE
AttributeError: 'BucketingSampler' object has no attribute 'world_size'

### ISSUE THREAD

**Issue by csukuangfj** [lhotse-speech/lhotse#221]
After updating to the latest master and regenerating the features for the librispeech dataset using https://github.com/k2-fsa/snowfall/pull/106, I encounter the following exception:

```bash
$ python3 ./mmi_bigram_embeddings_train.py
...
...

2021-03-08 11:36:29,363 INFO [mmi_bigram_embeddings_train.py:506] Using BucketingSampler.
Traceback (most recent call last):
  File "./mmi_bigram_embeddings_train.py", line 734, in <module>
    main()
  File "./mmi_bigram_embeddings_train.py", line 507, in main
    train_sampler = BucketingSampler(
  File "/root/fangjun/open-source/lhotse/lhotse/dataset/sampling.py", line 353, in __init__
    super().__init__(cuts[0].ids, world_size=1, rank=0, seed=seed)
  File "/root/fangjun/open-source/lhotse/lhotse/dataset/sampling.py", line 90, in __init__
    partition_cut_ids(self.full_data_source, world_size=self.world_size, rank=self.rank)
AttributeError: 'BucketingSampler' object has no attribute 'world_size'
```

@pzelasko  Do you have any idea how to resolve it?

**Comment by pzelasko** [comment]
Please check https://github.com/lhotse-speech/lhotse/pull/222 — it should help, let me know. Unofrtunately we don’t have unit tests for distributed samplers, but maybe there’s a way to create them...

**Comment by csukuangfj** [comment]
@pzelasko
Thanks! Your fix works.
