### ISSUE TITLE
error when dumping gigaspeech XL feature

### ISSUE THREAD

**Issue by glynpu** [lhotse-speech/lhotse#452]
Hi, Piotr@pzelasko 
I am trying to dump gigaspeech XL subset feature with this https://github.com/k2-fsa/icefall/pull/100. 
After 3.4G features extracted, the process is terminated unexpectly.

Question 1: Should I config something to fix this error?
Question 2: Is it possible to resume the extraction? i.e. Now 3.4G features are already extraced, how to avoid re-extacting feature of this part of utts?
Question 3: how big will feats_gigaspeech_XL.h5 be if everthing goes fine? Is it Around 1TG (since 10,000h XL = 1000 * 10h XS, and feats_gigaspeech_XS.h5 is 960M)? 

descriptions of related files:
```
-rw-r--r-- 1 guoliyong guoliyong 1.1M Nov  4 13:01 gigaspeech_cuts_XS_raw.jsonl.gz
-rw-r--r-- 1 guoliyong guoliyong 960M Nov  4 13:23 feats_gigaspeech_XS.h5
-rw-r--r-- 1 guoliyong guoliyong 998M Nov  4 17:32 gigaspeech_cuts_XL_raw.jsonl.gz
-rw-r--r-- 1 guoliyong guoliyong 3.4G Nov  5 07:19 feats_gigaspeech_XL.h5

```

Here is the log
```
Filtering OOV utterances from supervisions
Normalizing text in XL
Processing XL
About to split XL raw cuts into smaller chunks.
Computing features in batches:   0%|_                                                | 90663/24848964 [13:18:26<3634:01:08,  1.89it/s]
Traceback (most recent call last):
  File "prepare_gigaspeech.py", line 311, in <module>
    main()
  File "prepare_gigaspeech.py", line 267, in main
    cut_set = cut_set.compute_and_store_features_batch(
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/cut.py", line 3427, in compute_and_store_features_batch
    for batch in dloader:
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data    return self._process_data(data)  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data    data.reraise()  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 3.Original Traceback (most recent call last):  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 46, in fetch
    data = self.dataset[possibly_batched_index]
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/dataset/unsupervised.py", line 70, in __getitem__
    return {"cuts": cuts, "audio": [c.load_audio() for c in cuts]}
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/dataset/unsupervised.py", line 70, in <listcomp>
    return {"cuts": cuts, "audio": [c.load_audio() for c in cuts]}
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/cut.py", line 844, in load_audio
    return self.recording.load_audio(
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/audio.py", line 345, in load_audio
    samples = source.load_audio(
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/audio.py", line 128, in load_audio
    samples, sampling_rate = read_audio(
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/caching.py", line 70, in wrapper
    return m(*args, **kwargs)
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/audio.py", line 948, in read_audio
    return read_opus(
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/audio.py", line 1336, in read_opus
    channel_string = parse_channel_from_ffmpeg_output(proc.stderr)
  File "/ceph-ly/open-source/giga_librispeech/lhotse/lhotse/audio.py", line 1369, in parse_channel_from_ffmpeg_output
    raise ValueError(
ValueError: Could not determine the number of channels for OPUS file from the following ffmpeg output (shown as bytestring due to avoid possible encoding issues):
b''

```

**Comment by pzelasko** [comment]
> Question 1: Should I config something to fix this error? 

This seems like it might be some error in manifests. I'll try to add some extra exception handling in Lhotse later today to display the cut ID, so we can pinpoint which cut is creating the problem.

> Question 2: Is it possible to resume the extraction? i.e. Now 3.4G features are already extraced, how to avoid re-extacting feature of this part of utts? 

Not at the moment, but let me think about it -- I might have a idea how to add it. 

> Question 3: how big will feats_gigaspeech_XL.h5 be if everthing goes fine? Is it Around 1TG (since 10,000h XL = 1000 * 10h XS, and feats_gigaspeech_XL.h5 is 960M)?

That's true, it might end up being pretty large. I would either advise to compute them on-the-fly, or to add extra compression by controlling lilcom's `tick_size` (default is -5, I think -3 still works pretty much identical but I didn't test it too much). You can pass the lilcom argument like this:

```python
# Add the following imports
from functools import partial
from lhotse import LilcomHdf5Writer

cut_set = cut_set.compute_and_store_features_batch(
                         extractor=extractor,
                         storage_path=f"{output_dir}/feats_gigaspeech_{partition}",
                         batch_duration=args.batch_duration,
                         num_workers=args.num_workers,
                         # add the line below:
                         storage_type=partial(LilcomHdf5Writer, tick_power=-3),
                     )
```

I think HDF5 is also not the most space-efficient storage for uneven length arrays and variable-length byte sequences, but I don't have a good idea for any alternative backend atm.

@glynpu one more thing I noticed: you're not using `kaldifeat`, so you're not getting any speed benefit out of `_batch` feature extraction. To leverage `kaldifeat`, replace the following line:

```python
    extractor = Fbank(FbankConfig(num_mel_bins=80))
```

with:

```python
    extractor = KaldifeatFbank(KaldifeatFbankConfig(device='cuda'))  # default config uses 80 mel bins already
```

**Comment by pzelasko** [comment]
Hi @glynpu, can you check out the branch from this PR and tell me if it helps with your issues or provides new info for debugging? https://github.com/lhotse-speech/lhotse/pull/454

**Comment by danpovey** [comment]
Is there an easy way to split up a manifest into multiple pieces, and,
maybe, to recombine later?  I feel like, for Gigaspeech XL, it's too
much to hope that a single process will process it all without  crashing.

**Comment by pzelasko** [comment]
Yeah. 

In Python it’s: `cuts.split()` and `lhotse.combine(split1, split2, …)`

In CLI I think it’s `lhotse split <args>` and `lhotse combine <args>` 

There’s also a Python util that’s called `lhotse.split_parallelize_combine` which accepts an iterable and a function to apply to each split, but I don’t think it would play well with CUDA as-is.

But anyway my aim is not to crash even on large manifests… so if you run into bugs just let me know.

**Comment by glynpu** [comment]
It indeed give more error information. 
What should i do to avoid this?

LOG:
```
About to split DEV raw cuts into smaller chunks.                                                                             [52/1901]
Computing features in batches: 100%|____________________________________________________________| 5715/5715 [7:50:19<00:00,  4.94s/it]
Filtering OOV utterances from supervisions
Normalizing text in TEST
Processing TEST
About to split TEST raw cuts into smaller chunks.
Computing features in batches:  24%|______________                                          | 4722/19930 [4:03:04<13:02:51,  3.09s/it]
Traceback (most recent call last):
  File "./gpu_prepare_gigaspeech.py", line 315, in <module>
    main()
  File "./gpu_prepare_gigaspeech.py", line 270, in main
    cut_set = cut_set.compute_and_store_features_batch(
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/cut.py", line 3432, in compute_and_store_features_batch
    for batch in dloader:
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/utils.py", line 583, in wrapper
    return fn(*args, **kwargs)
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/audio.py", line 347, in load_audio
    samples = source.load_audio(
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/audio.py", line 145, in load_audio
    raise ValueError(
ValueError: Requested more audio (5.937s) than available (0.0s)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/utils.py", line 583, in wrapper
    return fn(*args, **kwargs)
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/cut.py", line 847, in load_audio
    return self.recording.load_audio(
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/utils.py", line 585, in wrapper
    raise type(e)(
ValueError: Requested more audio (5.937s) than available (0.0s)
[extra info] When calling: Recording.load_audio(args=(Recording(id='POD1000000040', sources=[AudioSource(type='file', channels=[0], so
urce='/home/storage07/zhangjunbo/data/GigaSpeech/audio/podcast/P0000/POD1000000040.opus')], sampling_rate=16000, num_samples=74568944,
 duration=4660.559, transforms=None),) kwargs={'channels': 0, 'offset': 3554.34, 'duration': 5.937})

During handling of the above exception, another exception occurred:
Traceback (most recent call last):                                                                                            [4/1901]
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 46, in fetch
    data = self.dataset[possibly_batched_index]
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/dataset/unsupervised.py", line 70, in __getitem__
    return {"cuts": cuts, "audio": [c.load_audio() for c in cuts]}
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/dataset/unsupervised.py", line 70, in <listcomp>
    return {"cuts": cuts, "audio": [c.load_audio() for c in cuts]}
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/utils.py", line 585, in wrapper
    raise type(e)(
ValueError: Requested more audio (5.937s) than available (0.0s)
[extra info] When calling: Recording.load_audio(args=(Recording(id='POD1000000040', sources=[AudioSource(type='file', channels=[0], so
urce='/home/storage07/zhangjunbo/data/GigaSpeech/audio/podcast/P0000/POD1000000040.opus')], sampling_rate=16000, num_samples=74568944,
 duration=4660.559, transforms=None),) kwargs={'channels': 0, 'offset': 3554.34, 'duration': 5.937})
[extra info] When calling: MonoCut.load_audio(args=(MonoCut(id='68cbe532-2f9d-4d2d-b745-9605fdfed0c6', start=3554.34, duration=5.937,
channel=0, supervisions=[SupervisionSegment(id='POD1000000040_S0000670', recording_id='POD1000000040', start=0.0, duration=5.937, chan
nel=0, text='SALE TODAY WE CHECK IT OUT EACH ONE OF THOSE THE BAGS NAMES LIKE IS NAMED AFTER ONE OF OUR KIDS LIKE THE WILLOW ', language='English', speaker='N/A', gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='POD1000000040', source
s=[AudioSource(type='file', channels=[0], source='/home/storage07/zhangjunbo/data/GigaSpeech/audio/podcast/P0000/POD1000000040.opus')]
, sampling_rate=16000, num_samples=74568944, duration=4660.559, transforms=None)),) kwargs={})
```

**Comment by pzelasko** [comment]
Hi @glynpu,

That's on me -- I didn't test the torchaudio OPUS reading carefully enough. It has more deviations from ffmpeg than I anticipated. 

I've just reverted this change in the latest commit to #454 -- try pulling and re-running, which will make Lhotse use ffmpeg again to read the audio. I tested that it works with the cut you reported.

BTW as a side note, I benchmarked torchaudio vs ffmpeg on the file with which you had issues. It turns out torchaudio seems to be 3x slower to read this file (see https://github.com/pytorch/audio/issues/1994). I think we're going to stick to ffmpeg, at least for now.

**Comment by pzelasko** [comment]
Hi @glynpu, did these changes solve your issues?

**Comment by glynpu** [comment]
The test is not finished because the IO speed from the  disk where gigaspeech locate is extremely slow (Another huge dataset is uploading to the storage). 
I will restart the test if disk is freed tomorrow.

**Comment by glynpu** [comment]
How long will it take to pre-compute "L" and "XL" subset features?
For the past whole night(around 14 hours I think)  6.7G features are dumped to disk. Since XS is around 10h and its feature is 960M. I think 6.7G feature is for around 70h dataset.

BTW, I am sure now ffmpeg backend is used rather than torch.audio. As when checked with "ps aux" command, there are lots of "ffmpeg" related progresses.

Is this speed as expected? or does it indicates I still have some IO issues?

**Comment by pzelasko** [comment]
Hmm that’s weird. I remember somebody else reporting it took 3h to extract a few thousand hours worth of features. It might be IO — you could check that with sth like iotop or nmon.

**Comment by csukuangfj** [comment]
>  I remember somebody else reporting it took 3h to extract a few thousand hours worth of features.

https://github.com/k2-fsa/icefall/issues/101#issuecomment-963109597

> Did you mean it takes about 4.5 hours to extract features for 6000 hours of audio on a single GPU?



https://github.com/lhotse-speech/lhotse/pull/422#issue-1027018196

> The RTF was 2000x faster than real-time (100h of audio in 3mins) on a slow-disk system (completely bottlenecked by I/O) with GTX1080Ti.

**Comment by pzelasko** [comment]
@glynpu are you sure that the extraction is taking place on GPU (ie kaldifeat is placed on CUDA device)?

**Comment by glynpu** [comment]
Yes, On GPU, I check it several times. Every time I run the script, 1348Mib / 32510Mib of GPU memory is instantly taken.

I think IO is the bottleneck. I make a rough exp: copying the dataset from gigaspeech datadir to the output feature dir(i.e. skip ffmpeg decoding and feature extraction).
With more than 3hours, only 60G under release dir(total release dir is 444G) is copied. 
Since the total is 10,000h, could I say 60G is around 1350h? So even the ffmpeg decoding and feature extraction takes no time, at most 1350h feature would be extracted with 3hours.

I am asking the advises from system maintainers to verify and solve this bottleneck issue if it indeed exist.

**Comment by glynpu** [comment]
Is it possible that the feature extraction will fail randomly?

I rerun the scripts several times, but one fails soon after the begging with following log:
```
Traceback (most recent call last):
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/ceph-ly/py38/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 46, in fetch
    data = self.dataset[possibly_batched_index]
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/dataset/unsupervised.py", line 70, in __getitem__
    return {"cuts": cuts, "audio": [c.load_audio() for c in cuts]}
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/dataset/unsupervised.py", line 70, in <listcomp>
    return {"cuts": cuts, "audio": [c.load_audio() for c in cuts]}
  File "/ceph-ly/open-source/giga_librispeech/master_lhotse/lhotse/lhotse/utils.py", line 585, in wrapper
    raise type(e)(
ValueError: Could not determine the number of channels for OPUS file from the following ffmpeg output (shown as bytestring due to avoid possible encoding issues):
b'Killed\n'
The ffmpeg command for which the program failed is: 'ffmpeg -ss 1034.03 -t 0.84 -i /home/storage07/zhangjunbo/data/GigaSpeech/audio/audiobook/P0005/AUD0000000465.opus -ar 16000 -f f32le pipe:1'
[extra info] When calling: Recording.load_audio(args=(Recording(id='AUD0000000465', sources=[AudioSource(type='file', channels=[0], source='/home/storage07/zhangjunbo/data/GigaSpeech/audio/audiobook/P0005/AUD0000000465.opus')], sampling_rate=16000, num_samples=78754448, duration=4922.153, transforms=None),) kwargs={'channels': 0, 'offset': 1034.03, 'duration': 0.84})
[extra info] When calling: MonoCut.load_audio(args=(MonoCut(id='e50361d8-92ef-4b1a-8734-4b01d057f37e', start=1034.03, duration=0.84, channel=0, supervisions=[SupervisionSegment(id='AUD0000000465_S0000184', recording_id='AUD0000000465', start=0.0, duration=0.84, channel=0, text='NOTHING ', language='English', speaker='N/A', gender=None, custom=None, alignment=None)], features=None, recording=Recording(id='AUD0000000465', sources=[AudioSource(type='file', channels=[0], source='/home/storage07/zhangjunbo/data/GigaSpeech/audio/audiobook/P0005/AUD0000000465.opus')], sampling_rate=16000, num_samples=78754448, duration=4922.153,
transforms=None)),) kwargs={})
```

**Comment by pzelasko** [comment]
Note the “Killed” message — something / somebody is killing your tasks. Maybe you’re running OOM on the node or using more resources than allocated? You can try decreasing batch size or num jobs, or ask around other users of your system for help.

**Comment by glynpu** [comment]
much faster if no trim_to_supervision/shuffle.

It only takes 20 minute that feats_gigaspeech_L.h5 increases to 3.8G, for around 40hours raw speech I think.
Is this acceleration as expected when I commented out following part?
```
                # Note this step makes the recipe different than LibriSpeech:       
                # Since recordings are long, the initial CutSet has very long cuts with a plenty of supervisions.        
                # We cut these into smaller chunks centered around each supervision, possibly adding acoustic        
                # context.                                                          
                print(f"About to split {partition} raw cuts into smaller chunks.")    
                # cut_set = cut_set.trim_to_supervisions(                           
                #     keep_overlapping=False,                                       
                #     min_duration=None                                             
                #     if args.context_window <= 0.0                                 
                #     else args.context_window,                                     
                #     context_direction=args.context_direction,                     
                # )                                                                 
                # if partition in ["L", "XL"]:                                      
                #     # Before storing manifests in, we want to pre-shuffle them,    
                #     # as Killedmpler won't be able to do it later in an efficient manner.
                # if partition in ["L", "XL"]:                                      
                #     # Before storing manifests in, we want to pre-shuffle them,    
                #     # as the sampler won't be able to do it later in an efficient manner.
                #     cut_set = cut_set.shuffle() 
```

**Comment by pzelasko** [comment]
Mm interesting. It only needs to open each file once so maybe this was the bottleneck for you. BTW if you extract the features first, but change storage_type to ChunkedLilcomHdf5Writer, and then trim to supervisions, it should work well for you. 

That would have been in the recipe in the first place, but it turned out computing features blew up the memory for long recordings. This is fixed with kaldifeat though, so as long as you are using it, it will work well.

**Comment by glynpu** [comment]
Shall we disable ffmpeg multi-thread?
It seems that defaultly ffmpeg will create num-cpus threads during decoding. 
Is this necessary? Or num-threads just make no differences?

Here is the screenshot of http when decoding with ffmpeg. 
![image](https://user-images.githubusercontent.com/14951566/142613851-cc530f75-1e08-4e2a-8af7-dd84f009bcaf.png)

**Comment by pzelasko** [comment]
That's a great find! I wasn't aware of this. Can you check if PR https://github.com/lhotse-speech/lhotse/pull/481 fixes this for you?

**Comment by wgb14** [comment]
Hi @glynpu, how are you dealing with speed issue and memory issue? Currently I'm using at most 2 workers, otherwise I'll get an OOM error. And with 2 workers, the progress bar tells me it will take about 6000h to finish feature extraction for XL set.

Are you doing splitting or extracting before trimming?

**Comment by csukuangfj** [comment]
> , the progress bar tells me it will take about 6000h to finish feature extraction for XL set.

Are you using GPU for feature extraction?

**Comment by wgb14** [comment]
> > , the progress bar tells me it will take about 6000h to finish feature extraction for XL set.
> 
> Are you using GPU for feature extraction?
Yes, I can see the GPU is allocated. But the GPU-Util is always 0%, working once every five minutes. Maybe it is always waiting for I/O.

**Comment by glynpu** [comment]
> how are you dealing with speed issue and memory issue? 

Sorry, I didn't solve this. As you can see, this issue is still open.

> Currently I'm using at most 2 workers, otherwise I'll get an OOM error

I tried following way to solve this OOM issue; Now I could set num-workers=30:
1. split the manifests with following command:
   ```
   lhotse split 2000 gigaspeech_cuts_L_raw.jsonl.gz split2000_manifests_L
   ```
2.  then a new dir "split2000_manifests_l" is created which contains 2000 small manifest files.
3.  then I extracted features one by one for these small manifest files with a LARGER num_workers 

> the progress bar tells me it will take about 6000h

I didn't solve this.  I thought the bottleneck may be ffmpeg decoding, so following is what I have tried: 
1. convert  the "TEST" related opus files to wavs
2. make a new manifest whose source pointing to these generated wavs; core mothods are:

   ```
    def new_cuts():                                                                     
        for i in range(len(cutset)):                                                    
            opus_path = cutset[i].recording.sources[0].source                           
            wav_id = os.path.basename(opus_path).split(".")[0] + ".wav"                 
            wav_path = Path("/ceph-ly/open-source/giga_librispeech/icefall/egs/librispeech/ASR/exp/new6/wavs") / wav_id
            # this assumes the related opus files are already converted to wav format; e.g. with shell commands
            cutset[i].recording.sources[0].source = str(wav_path)                                                                                                                                              
        cutset.to_file(Path("wav_gigaspeech_cuts_TEST_raw.jsonl.gz")) 
   ```  

3. profiling the extraction time with the original opus-manifest and this wav-manifests. As you may expect, no huge difference.

> Are you doing splitting or extracting before trimming?
   As previous mentioned, I tried to split the manifests, not work. 
   But no trimming may help, I think. As Piotr pointed above: "It only needs to open each file once so maybe this was the bottleneck for you"

Questions: 
How about the GPU-Util percentage when you extracting gigaspeech features?
Some of previous methods I tried affected the Memory-usage. 
But the GPU-util is always very low. It's always 0 expect at a very tiny-point it will increase to 40% and drop to 0% sharply.

**Comment by glynpu** [comment]
> Yes, I can see the GPU is allocated. But the GPU-Util is always 0%, working once every five minutes. Maybe it is always waiting for I/O.

Same to me even I am able to increase num-workers to 30. (I didn't notice this when I was replying just now)

**Comment by pzelasko** [comment]
Hmm this is not great. I’ll look into this more sometime this week.

**Comment by pzelasko** [comment]
After all the recent activity around GigaSpeech feature extraction, is it working now or is there something else I can do to help?

**Comment by csukuangfj** [comment]
I think there would be no issues about extracting features for GigaSpeech using https://github.com/k2-fsa/icefall/pull/120

**Comment by pzelasko** [comment]
Great, closing the issue then
