### ISSUE TITLE
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by jtrmal** [lhotse-speech/lhotse#535]
since Py 3.9 the function getchildren() in etree seems to be removed (was deprecated since long before, AFAIK)
Affects AMI corpus preparation
```
(py3) [jtrmal@test4 ami_lhotse]$ lhotse prepare ami --partition full-corpus-asr --normalize-text  /expscratch/mwiesner/miniscale_2022_data/Data/amicorpus .
2022-01-13 12:01:58,314 INFO [ami.py:554] Parsing AMI annotations
Traceback (most recent call last):
  File "/home/hltcoe/jtrmal/miniconda3/envs/py3/bin/lhotse", line 33, in <module>
    sys.exit(load_entry_point('lhotse', 'console_scripts', 'lhotse')())
  File "/home/hltcoe/jtrmal/miniconda3/envs/py3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/hltcoe/jtrmal/miniconda3/envs/py3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/hltcoe/jtrmal/miniconda3/envs/py3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hltcoe/jtrmal/miniconda3/envs/py3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hltcoe/jtrmal/miniconda3/envs/py3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hltcoe/jtrmal/miniconda3/envs/py3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/hltcoe/jtrmal/lhotse/lhotse/bin/modes/recipes/ami.py", line 47, in ami
    prepare_ami(
  File "/home/hltcoe/jtrmal/lhotse/lhotse/recipes/ami.py", line 565, in prepare_ami
    annotations = parse_ami_annotations(annotations_dir, normalize_text)
  File "/home/hltcoe/jtrmal/lhotse/lhotse/recipes/ami.py", line 342, in parse_ami_annotations
    assert len(seg.getchildren()) == 1, "Multiple child segments found"
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
```

**Comment by jtrmal** [comment]
@pzelasko let me know if I'm (not) right and if you want me to fix it

**Comment by pzelasko** [comment]
Thanks for reporting. I don't know about it as I rarely work with XML these days. If you know how to fix that, it'd be a welcome contribution.

**Comment by jtrmal** [comment]
ack, will do tomorrow.
y.

**Comment by jtrmal** [comment]
fixes are kinda trivial, I'm more surprised no-one has complained yet :) So I wonder if I'm just not doing something right

**Comment by pzelasko** [comment]
@jimbozhang and @desh2608 might know more as they are the main contributors of that recipe IIRC

**Comment by desh2608** [comment]
@jtrmal good catch! I didn't try the recipe with Python 3.9 so I wasn't aware of this issue (and somehow also missed deprecation warnings). I suppose the only change needed is seg.getchildren()--> list(seg). Could you make a PR with the fix?

**Comment by jtrmal** [comment]
yeah, will do
