### ISSUE TITLE
'CutSet' object is not callable

### ISSUE THREAD

**Issue by LasseWolter** [lhotse-speech/lhotse#549]
I'm trying to use Lhotse to load data from the ICSI-recording corpus. 

I'm using a very similar code to the example code from the docs. 
- My `speech/test`-dir only contains one directory (`Bdb001`) with one channel (`chan1.sph`) for fast debugging,
- My `transcripts/test`-dir contains the corresponding transcription: `Bdb001.mrt`

This is my test.py:
```
from torch.utils.data import DataLoader
from lhotse import CutSet, Fbank
from lhotse.dataset import VadDataset, SingleCutSampler
from lhotse.recipes import prepare_icsi
   
# Prepare data manifests from a raw corpus distribution.
# The RecordingSet describes the metadata about audio recordings;
# the sampling rate, number of channels, duration, etc.
# The SupervisionSet describes metadata about supervision segments:
# the transcript, speaker, language, and so on.
icsi, chan_idx_map = prepare_icsi(
    audio_dir='data/speech/test', transcripts_dir='data/transcripts/test', output_dir='lhotse_manifests')
    
# CutSet is the workhorse of Lhotse, allowing for flexible data manipulation.
# We create 5-second cuts by traversing SWBD recordings in windows.
# No audio data is actually loaded into memory or stored to disk at this point.
cuts = CutSet.from_manifests(
    recordings=icsi['train']['recordings'],
    supervisions=icsi['train']['supervisions']
).cut_into_windows(duration=5)   
   
# We compute the log-Mel filter energies and store them on disk;
# Then, we pad the cuts to 5 seconds to ensure all cuts are of equal length,
# as the last window in each recording might have a shorter duration.
# The padding will be performed once the features are loaded into memory.
cuts = cuts.compute_and_store_features(
    extractor=Fbank(),
    storage_path='feats',
    num_jobs=8
).pad(duration=5.0)
   
# Construct a Pytorch Dataset class for Voice Activity Detection task:
dataset = VadDataset(cuts)
sampler = SingleCutSampler(cuts, max_duration=300)
dataloader = DataLoader(dataset, sampler=sampler, batch_size=None)
batch = next(iter(dataloader))
```

The code above executes fine until the last line when this error is thrown: 

```
Parsing ICSI mrt files: 1it [00:00, 162.93it/s]
Preparing audio: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.97s/it]
Preparing supervision: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 2054.02it/s]
Extracting and storing features (chunks progress): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [03:41<00:00, 27.72s/it]
Traceback (most recent call last):
  File "<...>/test.py", line 35, in <module>
    batch = next(iter(dataloader))
  File "<...>/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "<...>lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "<...>/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = self.dataset[possibly_batched_index]
  File "<...>/lib/python3.9/site-packages/lhotse/dataset/vad.py", line 42, in __getitem__
    inputs, input_lens = self.input_strategy(cuts)
TypeError: 'CutSet' object is not callable
```

Has someone come across this before?

**Comment by pzelasko** [comment]
Sorry, the official example is misleading. Change the line:

```
dataset = VadDataset(cuts)
```

to

```
dataset = VadDataset()
```

Will push a fix.

**Comment by pzelasko** [comment]
See: https://github.com/lhotse-speech/lhotse/pull/550

**Comment by LasseWolter** [comment]
Amazing man, thanks for the quick response. 
Closing the issue
