### ISSUE TITLE
Using repeat() with dynamic bucketing

### ISSUE THREAD

**Issue by ngoel17** [lhotse-speech/lhotse#660]
I am trying to use repeat() on a lazy cutset followed by DynamicBycketingSampler. I ran into the following assert error. Obviously, the IDs will repeat if we repeat the cutset. what will be the best way to disable this error? 

2022-04-08 07:12:37,720 INFO [train.py:501] (0/8) Epoch 23, batch 71050, loss[loss=0.0924, over 5815 frames.], tot_loss[loss=0.1167, over 1155570.676405462 frames.], batch size: 6
Traceback (most recent call last):
  File "/mnt/dsk2/icefall/egs/k2/./transducer_stateless/train.py", line 760, in <module>
    main()
  File "/mnt/dsk2/icefall/egs/k2/./transducer_stateless/train.py", line 751, in main
    mp.spawn(run, args=(world_size, args), nprocs=world_size, join=True)
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/home/ngoel/lhotse/lhotse/dataset/sampling/dynamic.py", line 222, in _collect_batch
    next_cut_or_tpl = next(self.cuts_iter)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/mnt/dsk2/icefall/egs/k2/transducer_stateless/train.py", line 677, in run
    train_one_epoch(
  File "/mnt/dsk2/icefall/egs/k2/transducer_stateless/train.py", line 470, in train_one_epoch
    for batch_idx, batch in enumerate(train_dl):
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1192, in _next_data
    return self._process_data(data)
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1236, in _process_data
    self._try_put_index()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1218, in _try_put_index
    index = self._next_index()
  File "/home/ngoel/anaconda3/envs/k2/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/ngoel/lhotse/lhotse/dataset/sampling/base.py", line 245, in __next__
    batches.append(self._next_batch())
  File "/home/ngoel/lhotse/lhotse/dataset/sampling/dynamic_bucketing.py", line 177, in _next_batch
    batch = next(self.cuts_iter)
  File "/home/ngoel/lhotse/lhotse/dataset/sampling/dynamic_bucketing.py", line 316, in __iter__
    batch = next(iter(batcher))
  File "/home/ngoel/lhotse/lhotse/dataset/sampling/dynamic.py", line 190, in __iter__
    yield self._collect_batch()
  File "/home/ngoel/lhotse/lhotse/dataset/sampling/dynamic.py", line 231, in _collect_batch
    return detuplify(cuts)
  File "/home/ngoel/lhotse/lhotse/dataset/sampling/dynamic.py", line 202, in detuplify
    cuts = CutSet.from_cuts(cs[0] for cs in cuts)
  File "/home/ngoel/lhotse/lhotse/cut.py", line 3392, in from_cuts
    return CutSet(cuts=index_by_id_and_check(cuts))
  File "/home/ngoel/lhotse/lhotse/utils.py", line 530, in index_by_id_and_check
    assert m.id not in id2man, f"Duplicated manifest ID: {m.id}"
AssertionError: Duplicated manifest ID: af2a8ce4-c56a-4370-8076-5b8d97f63968_sp1.1

**Comment by pzelasko** [comment]
The easiest way may be to modify the IDs, sth like:

```python
class CutIdModifier:
    def __init__(self):
        self.idx = 0

    def __call__(self, cut):
        cut.id = f"{cut.id}-{self.idx}"
        self.idx = (self.idx + 1) % 100000
        return cut
    
cuts = cuts.repeat().map(CutIdModifier())
```

**Comment by ngoel17** [comment]
@pzelasko  - Just FYI - the repeat() approach combined with Mux does improve the WER, a 1.3% reduction at less than 10% WER starting point is a good number to have.  I  think that repeat() itself should change the id instead of doing it outside of repeat() because every time someone uses repeat() this issue will occur otherwise.

**Comment by pzelasko** [comment]
Cool! Thanks for letting me know! 

Good idea to add an option to repeat that changes the ids.

**Comment by pzelasko** [comment]
Added in PR https://github.com/lhotse-speech/lhotse/pull/699, now the IDs are changed by default, which can be turned off.

**Comment by ngoel17** [comment]
Your syntax puts it outside the repeat. I think maybe "repeat count" could
go inside the repeat() method itself so that IDs are always modified
whenever repeat is used, because repeat will fail without the ID
modification. Right?

**Comment by pzelasko** [comment]
Can you describe the issue? If you use the current Lhotse version, it auto-modifies the IDs when using repeat.

**Comment by ngoel17** [comment]
Is this directed towards me. I used repeat() successfully recently.

**Comment by pzelasko** [comment]
Yes, you posted 3h ago on this thread (see below). Maybe it's an old email that just got sent? :)

> Your syntax puts it outside the repeat. I think maybe "repeat count" could go inside the repeat() method itself so that IDs are always modified whenever repeat is used, because repeat will fail without the ID modification. Right?
> […](#)
