### ISSUE TITLE
Object of type 'LazyFilter' has no len()

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#691]
I'm running into this weird issue, and I'm not sure why adding manifests should create a lazy iterator?

```python
In [5]: m = prepare_ali_meeting('/export/c01/corpora6/AliMeeting')
Preparing Train: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 209/209 [02:56<00:00,  1.19it/s]
WARNING:root:Removed 241 supervisions starting after the end of the recording.
WARNING:root:Trimmed 5 supervisions exceeding the end of the recording.
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4026 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4028 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4030 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 4 supervisions that start at 0 for recording R1019_M4031 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4033 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4035 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4039 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4041 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4043 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1019_M4051 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 4 supervisions that start at 0 for recording R1019_M4052 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1021_M1935 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1021_M1942 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1021_M1944 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1021_M1959 (channel 0). Did you forget to set supervision start times?
WARNING:root:SupervisionSet contains 2 supervisions that start at 0 for recording R1021_M1961 (channel 0). Did you forget to set supervision start times?
Preparing Eval: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 10.20it/s]
Preparing Test: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 11.17it/s]

In [6]: s = m["eval"]["supervisions"]

In [7]: s1 = s.filter(lambda seg: seg.duration >= 0.5)

In [8]: len(s1)
Out[8]: 5193

In [9]: s = m["eval"]["supervisions"] + m["test"]["supervisions"]

In [10]: s1 = s.filter(lambda seg: seg.duration >= 0.5)
/export/c07/draj/lhotse/lhotse/lazy.py:327: UserWarning: A lambda was passed to LazyFilter: it may prevent you from forking this process. If you experience issues with num_workers > 0 in torch.utils.data.DataLoader, try passing a regular function instead.
  "A lambda was passed to LazyFilter: it may prevent you from forking this process. "

In [11]: len(s1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-a700e8f68e2d> in <module>
----> 1 len(s1)

/export/c07/draj/lhotse/lhotse/supervision.py in __len__(self)
    815
    816     def __len__(self) -> int:
--> 817         return len(self.segments)

TypeError: object of type 'LazyFilter' has no len()
```

Any suggestions?

**Comment by pzelasko** [comment]
You can call .to_eager() on the resulting manifest to evaluate the expression. I started moving multiple operations to lazy evaluation a while ago, the only downside I can see is missing len. It’s just an extra function call away and for that we get memory-friendly behavior by default.

**Comment by desh2608** [comment]
I ran into the issue when calling `fix_manifests()` since it cheks the `len()` of the manifests. Perhaps there should be a conversion to eager mode if the manifests are lazy?

**Comment by pzelasko** [comment]
Hmm yeah that code was written before I got the idea with lazy manifests. We’d need to adapt it somehow or make some checks optional and emit warnings if it’s impossible to run them on lazy manifests. I’d avoid auto-triggering eager evaluation because the input may be MLS sized, which will typically crash the machine.

**Comment by desh2608** [comment]
We should perhaps fix this issue with high priority, because it breaks down recipes that use `fix_manifests()`, such as the following error in Fisher English recipe:

```python
Parsing audio sub-dirs: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 118/118 [00:00<00:00, 138.25it/s]
Parsing transcript sub-dirs: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 118/118 [00:01<00:00, 114.10it/s]
2022-05-18 21:03:06,917 INFO [fisher_english.py:200] Building fresh recording manifest
Collect recordings: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11699/11699 [1:43:11<00:00,  1.89it/s]
/exp/draj/mini_scale_2022/lhotse/lhotse/recipes/fisher_english.py:218: UserWarning: Out of 11699 recordings, 3 had errors and were omitted.
  warnings.warn(
2022-05-18 22:46:18,902 INFO [fisher_english.py:229] Building fresh supervision manifest
Create supervisions: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11699/11699 [03:37<00:00, 53.70it/s]
/exp/draj/mini_scale_2022/lhotse/lhotse/recipes/fisher_english.py:248: UserWarning: Out of 11699 transcript files, 0 had errors and were omitted.
  warnings.warn(
/exp/draj/mini_scale_2022/lhotse/lhotse/lazy.py:328: UserWarning: A lambda was passed to LazyFilter: it may prevent you from forking this process. If you experience issues with num_workers > 0 in torch.utils.data.DataLoader, try passing a regular function instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/hltcoe/draj/.conda/envs/scale/bin/lhotse", line 33, in <module>
    sys.exit(load_entry_point('lhotse', 'console_scripts', 'lhotse')())
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/exp/draj/mini_scale_2022/lhotse/lhotse/bin/modes/recipes/fisher_english.py", line 58, in fisher_english
    prepare_fisher_english(
  File "/exp/draj/mini_scale_2022/lhotse/lhotse/recipes/fisher_english.py", line 253, in prepare_fisher_english
    recordings, supervisions = fix_manifests(recordings, supervisions)
  File "/exp/draj/mini_scale_2022/lhotse/lhotse/qa.py", line 61, in fix_manifests
    recordings, supervisions = remove_missing_recordings_and_supervisions(
  File "/exp/draj/mini_scale_2022/lhotse/lhotse/qa.py", line 153, in remove_missing_recordings_and_supervisions
    n_removed_sups = n_orig_sups - len(supervisions)
  File "/exp/draj/mini_scale_2022/lhotse/lhotse/supervision.py", line 817, in __len__
    return len(self.segments)
TypeError: object of type 'LazyFilter' has no len()
```

Do you have a suggestion for how it should be handled? I can make the required changes and create a PR.

**Comment by pzelasko** [comment]
we can either

1) replace some integrity checks/fixes like `remove_missing_recordings_and_supervisions` with a two-pass strategy that first iterates to get the sets of compatible/incompatible IDs, and in the second pass filters out the incompatible ones.

or

2) read everything into memory with `manifest.to_eager()` (will break for people with not enough CPU RAM and large data)

**Comment by jtrmal** [comment]
I think unless you introduce some additional constrain on the lazy
manifests (such as being sorted by ID), you will have to give up on (easy)
sanity checks.
y.

**Comment by pzelasko** [comment]
Yeah, I guess you're right. I probably would leave it as-is for now, unless you'd like to improve it further.
