### ISSUE TITLE
RuntimeError in `compute_and_store_features_batch()`

### ISSUE THREAD

**Issue by desh2608** [lhotse-speech/lhotse#717]
I was trying to compute `kaldifeat` features for a CutSet using `compute_and_store_features_batch()`, but ran into the following error. This occurred after some iterations had already processed successfully.

```python
Traceback (most recent call last):
  File "local/compute_fbank_ami.py", line 160, in <module>
    compute_fbank_ami()
  File "local/compute_fbank_ami.py", line 102, in compute_fbank_ami
    cuts_train = cuts_train.compute_and_store_features_batch(
  File "/exp/draj/mini_scale_2022/lhotse/lhotse/cut.py", line 4729, in compute_and_store_features_batch
    for batch in dloader:
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/multiprocessing/reduction.py", line 189, in recv_handle
    return recvfds(s, 1)[0]
  File "/home/hltcoe/draj/.conda/envs/scale/lib/python3.8/multiprocessing/reduction.py", line 164, in recvfds
    raise RuntimeError('received %d items of ancdata' %
RuntimeError: received 0 items of ancdata
```

Previosly I used the same function successfully for smaller cut sets. This particular cut set contains approx. 600k cuts. On searching for the error, I found [this thread](https://discuss.pytorch.org/t/runtimeerror-received-0-items-of-ancdata/4999/4) which suggests that the cause may be memory leak in the dataloader. Any ideas/suggestions? Is it recommended to split large cut sets into smaller parts for feature extraction? (I split SPGISpeech train set into 20 parts, but I figured that was mainly for storage purposes.)

**Comment by desh2608** [comment]
It seems it may also be a result of too many file handles: https://github.com/pytorch/pytorch/issues/11201

**Comment by pzelasko** [comment]
I'm pretty sure I ran into this once or twice, I think it may be related to excessive use of system resources such as file handles, but I don't know how you would actually go about debugging it. What usually works is decreasing the number of dataloader workers or the batch size (is it possible you set them high to try and max out the GPU usage?).

**Comment by desh2608** [comment]
When using the same batch size and number of workers but with a smaller cut set I didn't run into any errors, so I am not sure if it is related to GPU memory usage. On adding the following snipper (suggested on the link above), it works without issues:
```python
torch.multiprocessing.set_sharing_strategy('file_system')
```
It does seem to be system resource issue so I'll close it for now.
