### ISSUE TITLE
Error downloading voxceleb dataset 

### ISSUE THREAD

**Issue by mikuchar** [lhotse-speech/lhotse#754]
Neither cli call nor `download_voxceleb1` method call is working to download voxceleb dataset
**Expected**: Successful download and extraction of the corpus
**Actual:**
```
!lhotse download voxceleb1 /content/vox1/
Downloading VoxCeleb1 vox1_dev_wav_partaa: 100% 10.0G/10.0G [07:55<00:00, 22.6MB/s]
Downloading VoxCeleb1 vox1_dev_wav_partab: 100% 10.0G/10.0G [07:52<00:00, 22.7MB/s]
Downloading VoxCeleb1 vox1_dev_wav_partac: 100% 10.0G/10.0G [07:59<00:00, 22.4MB/s]
Downloading VoxCeleb1 vox1_dev_wav_partad: 367MB [00:18, 20.5MB/s]               
Downloading VoxCeleb1 vox1_test_wav.zip: 1.00GB [00:48, 22.1MB/s]                
2022-06-22 05:51:33,708 INFO [voxceleb.py:112] Unzipping dev...
Traceback (most recent call last):
  File "/usr/local/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/lhotse/bin/modes/recipes/voxceleb.py", line 15, in voxceleb1
    download_voxceleb1(target_dir, force_download=force_download)
  File "/usr/local/lib/python3.7/dist-packages/lhotse/recipes/voxceleb.py", line 113, in download_voxceleb1
    with zipfile.ZipFile(zip_path) as zf:
  File "/usr/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/content/vox1/vox1_dev_wav.zip'
```
**Problem:**
zip chunks are downloaded to a temporary files with random names. Script expects original file names in the target directory.
**Possible fix:** 
Introduce temp directory with original names

**Comment by desh2608** [comment]
Fixed in https://github.com/lhotse-speech/lhotse/pull/776.
