### ISSUE TITLE
Pad CutSet with silence?

### ISSUE THREAD

**Issue by danpovey** [lhotse-speech/lhotse#779]
I'm wondering whether there is an easy way to pad all the cuts in a CutSet with a fixed amount of silence on the sides, as in extend()?  This is for things like debugging edge issues with models, or decoding and making sure final symbols are output.
I tried extend_by(), but it appears to be a no-op, e.g.
`a.extend_by(0.05, preserve_id=True).fill_supervisions()`
seemed to return the original CutSet (possibly because it only extended to the edge of the original recordings?)
I ended up doing this with something like:
```
 load_manifest(self.args.manifest_dir / "cuts_test-clean.json.gz").pad(direction='both').fill_supervisions()
```
just for testing purposes, which isn't ideal because it make all utterances as long as the longest one, which is not what I really wanted.

**Comment by pzelasko** [comment]
Try this one https://github.com/lhotse-speech/lhotse/blob/master/lhotse/dataset/cut_transforms/extra_padding.py by passing it to the Dataset as a cut transform.

**Comment by danpovey** [comment]
When I add the cut_transforms line below:
```
        test = K2SpeechRecognitionDataset(
            input_strategy=OnTheFlyFeatures(Fbank(FbankConfig(num_mel_bins=80)))
            if self.args.on_the_fly_feats
            else eval(self.args.input_strategy)(),
            cut_transforms=[ExtraPadding(extra_frames=10)],
            return_cuts=self.args.return_cuts,
        )
```
I get the following error, likely because it is not doing fill_supervisions():
```

/ceph-dan/.local/lib/python3.8/site-packages/lhotse-1.3.0.dev0+git.4198446.clean-py3.8.egg/lhotse/dataset/sampling/dynamic_bucketing.py:121: UserWarning: You are using DynamicBucketingSampler with an eagerly read CutSet. You won\
't see any memory/speed benefits with that setup. Either use 'CutSet.from_jsonl_lazy' to read the CutSet lazily, or use a BucketingSampler instead.
Traceback (most recent call last):
  File "./pruned_transducer_stateless7/decode.py", line 635, in <module>
    main()
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "./pruned_transducer_stateless7/decode.py", line 617, in main
    results_dict = decode_dataset(
  File "./pruned_transducer_stateless7/decode.py", line 385, in decode_dataset
    hyps_dict = decode_one_batch(
  File "./pruned_transducer_stateless7/decode.py", line 265, in decode_one_batch
    encoder_out, encoder_out_lens = model.encoder(
  File "/ceph-dan/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ceph-dan/icefall/egs/librispeech/ASR/pruned_transducer_stateless7/conformer.py", line 127, in forward
    assert x.size(0) == lengths.max().item()
AssertionError
```

**Comment by pzelasko** [comment]
Hmm I suppose you can call it on the full CutSet and then call fill_supervisions. Maybe I can add it as a CutSet method later for convenience.

**Comment by danpovey** [comment]
OK, I am adding silence in test time by adding code like the following in asr_datamodule.py:
```
    @lru_cache()
    def test_clean_cuts(self) -> CutSet:
        logging.info("About to get test-clean cuts")
        return ExtraPadding(extra_frames=10, pad_feat_value=-8.0)(load_manifest(self.args.manifest_dir / "cuts_test-clean.json.gz")).fill_supervisions()
```
(I tried values like extra_frames={10,100} and pad_feat_value={-8,default=-23}).  Unfortunately, there doesn't seem to be a setting which gives great WER results; as we add more extra frames we see more of the BOS insertions but fewer of the BOS deletions.

**Comment by desh2608** [comment]
I guess we could add a boolean argument `pad_silence to the `extend_by()` function which specifies whether to pad the cut with silence if not enough context is present.

**Comment by pzelasko** [comment]
Sounds good!

**Comment by desh2608** [comment]
Closing via https://github.com/lhotse-speech/lhotse/pull/816.
