### ISSUE TITLE
lhotse

### ISSUE THREAD

**Issue by yuyhee** [lhotse-speech/lhotse#794]
Building wheel for lilcom (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      /root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/dist.py:774: UserWarning: Usage of dash-separated 'index-url' will not be supported in future versions. Please use the underscore name 'index_url' instead
        % (opt, underscore_opt)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-37
      creating build/lib.linux-x86_64-cpython-37/lilcom
      copying lilcom/lilcom_interface.py -> build/lib.linux-x86_64-cpython-37/lilcom
      copying lilcom/__init__.py -> build/lib.linux-x86_64-cpython-37/lilcom
      running build_ext
      Setting PYTHON_EXECUTABLE to /root/anaconda3/envs/foo/bin/python3.7
      For fast compilation, run:
      export LILCOM_MAKE_ARGS="-j"; python setup.py install
      build command is:
      
                      cd build/temp.linux-x86_64-cpython-37
      
                      cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=/root/anaconda3/envs/foo/bin/python3.7 /tmp/pip-install-2kv1rtt3/lilcom_bf00a0a8d6394af88a3a6ec3dc47caa5
      
      
                      make  lilcom_extension
      
      sh: 4: cmake: not found
      make: *** No rule to make target 'lilcom_extension'.  Stop.
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2kv1rtt3/lilcom_bf00a0a8d6394af88a3a6ec3dc47caa5/setup.py", line 73, in <module>
          "License :: OSI Approved :: MIT License",
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/root/anaconda3/envs/foo/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-install-2kv1rtt3/lilcom_bf00a0a8d6394af88a3a6ec3dc47caa5/cmake/cmake_extension.py", line 102, in build_extension
          "\nBuild lilcom failed. Please check the error message.\n"
      Exception:
      Build lilcom failed. Please check the error message.
      You can ask for help by creating an issue on GitHub.
      
      Click:
          https://github.com/danpovey/lilcom/issues/new
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lilcom

**Comment by csukuangfj** [comment]
>   sh: 4: cmake: not found

From the error log, please install `cmake` first.

**Comment by pzelasko** [comment]
`pip install -U cmake` should be sufficient
