### ISSUE TITLE
libpython3.8.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by WangHelin1997** [lhotse-speech/lhotse#800]
How to fix that problem?
Thanks!

```
(icefall_armory_june22) hwang258@b01:~/codes/icefall/egs/yesno/ASR$ python
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lhotse
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hwang258/anaconda3/envs/icefall_armory_june22/lib/python3.8/site-packages/lhotse/__init__.py", line 8, in <module>
    from .cut import CutSet, MonoCut, create_cut_set_eager, create_cut_set_lazy
  File "/home/hwang258/anaconda3/envs/icefall_armory_june22/lib/python3.8/site-packages/lhotse/cut.py", line 46, in <module>
    from lhotse.features import (
  File "/home/hwang258/anaconda3/envs/icefall_armory_june22/lib/python3.8/site-packages/lhotse/features/__init__.py", line 1, in <module>
    from .base import (
  File "/home/hwang258/anaconda3/envs/icefall_armory_june22/lib/python3.8/site-packages/lhotse/features/base.py", line 19, in <module>
    from lhotse.features.io import FeaturesWriter, get_reader
  File "/home/hwang258/anaconda3/envs/icefall_armory_june22/lib/python3.8/site-packages/lhotse/features/io.py", line 9, in <module>
    import lilcom
  File "/home/hwang258/anaconda3/envs/icefall_armory_june22/lib/python3.8/site-packages/lilcom/__init__.py", line 2, in <module>
    from .lilcom_interface import compress, decompress, get_shape
  File "/home/hwang258/anaconda3/envs/icefall_armory_june22/lib/python3.8/site-packages/lilcom/lilcom_interface.py", line 3, in <module>
    import lilcom_extension
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by csukuangfj** [comment]
How did you install `lilcom`?

Do you have the logs for `lilcom` installation?

**Comment by davidlin409** [comment]
I do have encounter similar situation. 

I am using Python 3.10 (Conda environement). I install `lhotse` according to documentation, using `PIP` package manager. I install `PIP` package directly from PYPI, instead of using GIT to fetch code and compile.

I don't have orignal log in installing `lilcom`, and I just obtain log from "reinstalling `lilcom`":

```
Collecting lilcom
  Using cached lilcom-1.4-py3-none-any.whl
Collecting numpy<1.23.0
  Using cached numpy-1.22.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
Installing collected packages: numpy, lilcom
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
  Attempting uninstall: lilcom
    Found existing installation: lilcom 1.4
    Uninstalling lilcom-1.4:
      Successfully uninstalled lilcom-1.4
Successfully installed lilcom-1.4 numpy-1.22.4
```

**Comment by csukuangfj** [comment]
What is the output of
```
find $CONDA_PREFIX -name "libpython*"
```

You may need to use
```
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
```
if you can find libpython3.8.so.1.0 inside `$CONDA_PREFIX/lib`.

**Comment by davidlin409** [comment]
Yes, indeed using export is one method to solve the issue.

------------------------

But there is another way that is way more cleaner:

I tries to force-install `lilcom` from `miniconda`, which directly solve "library not found" issue without the need to export `LD_LIBRARY_PATH`. 

Since that lots of people follow documentation to install `lhotse`. Maybe documentation can add statement like below? 

> If Python is installed via Miniconda/Anaconda, it is suggested to install `lilcom` package first via Miniconda/Anaconda, before installing `lhotse`.

By that method, other people can avoid encounting this issue (since first time encoutering this issue have trouble finding issue #800 by search).

**Comment by davidlin409** [comment]
Indeed export cna resolve the issue for short term.

------------------------

There is another way that does not requires "export".

I tries to force-install `lilcom` from Miniconda via `lilcom` channel, and the issue is also resolved.

Maybe in documentation, explanation can be added to advice user to install `lilcom` from Miniconda/Anaconda if user's Python is installed from there?

**Comment by csukuangfj** [comment]
> Indeed export cna resolve the issue for short term.
> 
> There is another way that does not requires "export".
> 
> I tries to force-install `lilcom` from Miniconda via `lilcom` channel, and the issue is also resolved.
> 
> Maybe in documentation, explanation can be added to advice user to install `lilcom` from Miniconda/Anaconda if user's Python is installed from there?

@davidlin409 
It should be fixed in https://github.com/danpovey/lilcom/pull/48

Please use the latest lilcom (v1.5). You don't need to set `LD_LBIRARY_PATH` any more.

**Comment by davidlin409** [comment]
Indeed that solve the `LD_LBIRARY_PATH` completely. Thank you very much for such fast fix 😄.
