### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by KajiMaCN** [lhotse-speech/lhotse#821]
window10 python3.8 pytorch==1.12.1 cpu_only
logs:
(ice_fall2) PS D:\PyCharm Projects\ASR> pip install lhotse -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting lhotse
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/39/54/544d854dd4da79c433438bf43fbaf9927789089c13dca847f087724b9522/lhotse-1.7.0-py3-none-any.whl 
(497 kB)
Collecting pyyaml>=5.3.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a8/5b/c4d674846ea4b07ee239fbf6010bcc427c4e4552ba5655b446e36b9a40a7/PyYAML-6.0-cp38-cp38-win_amd64
.whl (155 kB)
Collecting dataclasses
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/26/2f/1095cdc2868052dd1e64520f7c0d5c8c550ad297e944e641dbf1ffbb9a5d/dataclasses-0.6-py3-none-any.w
hl (14 kB)
Collecting cytoolz>=0.10.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3d/92/80eefb6fcde8c7c3d735021a6db2085ebfd7754154bcc0cf256038221d6f/cytoolz-0.12.0-cp38-cp38-win_a
md64.whl (330 kB)
Collecting audioread>=2.1.9
  Using cached audioread-3.0.0-py3-none-any.whl
Collecting SoundFile>=0.10
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b8/de/24e4035f06540ebb4e9993238ede787063875b003e79c537511d32a74d29/SoundFile-0.10.3.post1-py2.py3
.cp26.cp27.cp32.cp33.cp34.cp35.cp36.pp27.pp32.pp33-none-win_amd64.whl (689 kB)
Collecting click>=7.1.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl (
96 kB)
Collecting intervaltree>=3.1.0
  Using cached intervaltree-3.1.0-py2.py3-none-any.whl
Collecting packaging
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.wh
l (40 kB)
Collecting lilcom>=1.1.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/38/14/9f82e7c93186eae26eaf2c4462bb08a1e234d18822e50e4356c82bb1d837/lilcom-1.3.tar.gz (44 kB)
  Preparing metadata (setup.py) ... done
Collecting tqdm
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.w
hl (78 kB)
Requirement already satisfied: numpy>=1.18.1 in d:\anaconda3\envs\ice_fall2\lib\site-packages (from lhotse) (1.23.3)
Collecting colorama
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/77/8b/7550e87b2d308a1b711725dfaddc19c695f8c5fa413c640b2be01662f4e6/colorama-0.4.5-py2.py3-none-an
y.whl (16 kB)
Collecting toolz>=0.8.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7f/5c/922a3508f5bda2892be3df86c74f9cf1e01217c2b1f8a0ac4841d903e3e9/toolz-0.12.0-py3-none-any.whl 
(55 kB)
Collecting sortedcontainers<3.0,>=2.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3
-none-any.whl (29 kB)
Collecting numpy>=1.18.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/17/3d/81208f0cf5f2885d00294589fe9adc6ecc985f898f1007781e66cb85230a/numpy-1.22.4-cp38-cp38-win_amd
64.whl (14.8 MB)
Collecting cffi>=1.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c9/e3/0a52838832408cfbbf3a59cb19bcd17e64eb33795c9710ca7d29ae10b5b7/cffi-1.15.1-cp38-cp38-win_amd6
4.whl (178 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.w
hl (98 kB)
Collecting pycparser
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-an
y.whl (118 kB)
Building wheels for collected packages: lilcom
  Building wheel for lilcom (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [61 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\lilcom
      copying lilcom\lilcom_interface.py -> build\lib.win-amd64-cpython-38\lilcom
      copying lilcom\__init__.py -> build\lib.win-amd64-cpython-38\lilcom
      running build_ext
      'cmake' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\JHC-L1022\AppData\Local\Temp\pip-install-gfsqnnh8\lilcom_32ac5509b3d54238a49c013a4736da54\setup.py", line 52, in <module>
          setuptools.setup(
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\JHC-L1022\AppData\Local\Temp\pip-install-gfsqnnh8\lilcom_32ac5509b3d54238a49c013a4736da54\cmake\cmake_extension.py", line 77, in bui
ld_extension
          raise Exception("Failed to build lilcom_extension")
      Exception: Failed to build lilcom_extension
      Setting PYTHON_EXECUTABLE to D:\Anaconda3\envs\ice_fall2\python.exe
      build command is:
     
                      cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=D:\Anaconda3\envs\ice_fall2\python.exe -B build\temp.win-amd64-cpython-38\Releas
e -S C:\Users\JHC-L1022\AppData\Local\Temp\pip-install-gfsqnnh8\lilcom_32ac5509b3d54238a49c013a4736da54
                      cmake --build build\temp.win-amd64-cpython-38\Release --target lilcom_extension --config Release -- -m
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lilcom
  Running setup.py clean for lilcom
Failed to build lilcom
Installing collected packages: sortedcontainers, dataclasses, toolz, pyyaml, pyparsing, pycparser, numpy, intervaltree, colorama, audioread, tqdm, packagin
g, lilcom, cytoolz, click, cffi, SoundFile, lhotse
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.3
    Uninstalling numpy-1.23.3:
      Successfully uninstalled numpy-1.23.3
  Running setup.py install for lilcom ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lilcom did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running install
      D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use bui
ld and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\lilcom
      copying lilcom\lilcom_interface.py -> build\lib.win-amd64-cpython-38\lilcom
      copying lilcom\__init__.py -> build\lib.win-amd64-cpython-38\lilcom
      running build_ext
      'cmake' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\JHC-L1022\AppData\Local\Temp\pip-install-gfsqnnh8\lilcom_32ac5509b3d54238a49c013a4736da54\setup.py", line 52, in <module>
          setuptools.setup(
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\dist.py", line 992, in run_command
          cmd_obj.run()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
          self.build_extensions()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "D:\Anaconda3\envs\ice_fall2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\Users\JHC-L1022\AppData\Local\Temp\pip-install-gfsqnnh8\lilcom_32ac5509b3d54238a49c013a4736da54\cmake\cmake_extension.py", line 77, in bui
ld_extension
          raise Exception("Failed to build lilcom_extension")
      Exception: Failed to build lilcom_extension
      Setting PYTHON_EXECUTABLE to D:\Anaconda3\envs\ice_fall2\python.exe
      build command is:
     
                      cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=D:\Anaconda3\envs\ice_fall2\python.exe -B build\temp.win-amd64-cpython-38\Releas
e -S C:\Users\JHC-L1022\AppData\Local\Temp\pip-install-gfsqnnh8\lilcom_32ac5509b3d54238a49c013a4736da54
                      cmake --build build\temp.win-amd64-cpython-38\Release --target lilcom_extension --config Release -- -m
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lilcom

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by csukuangfj** [comment]
Please run

pip install cmake

and retry.

**Comment by csukuangfj** [comment]
Yes, it is doable. Will create a PR.

**Comment by pzelasko** [comment]
I don't mind if you could help, I never used pybind11 before.

**Comment by KajiMaCN** [comment]
> Please run
> 
> pip install cmake
> 
> and retry.

Thanks, it worked.
