### ISSUE TITLE
[Common Voice] Can't load prepared cv-en_supervisions_dev.jsonl.gz

### ISSUE THREAD

**Issue by trunglebka** [lhotse-speech/lhotse#969]
Hi, I've encountered the following error while loading common voice prepared cv-en_supervisions_dev.jsonl.gz
```
Traceback (most recent call last):
  File "/home/chicky/opt/anaconda3/envs/k2/bin/lhotse", line 8, in <module>
    sys.exit(cli())
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/lhotse/bin/modes/manipulation.py", line 31, in copy
    data = load_manifest_lazy_or_eager(input_manifest)
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/lhotse/serialization.py", line 480, in load_manifest_lazy_or_eager
    return load_manifest_lazy(path)
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/lhotse/serialization.py", line 464, in load_manifest_lazy
    first = next(raw_data)
  File "/home/chicky/opt/anaconda3/envs/k2/lib/python3.10/site-packages/lhotse/serialization.py", line 134, in load_jsonl
    ret = decode_json_line(line)
orjson.JSONDecodeError: unexpected character: line 1 column 341 (char 340)
```

Common Voice version: `cv-corpus-12.0-2022-12-07/en`

First few lines of cv-en_supervisions_dev.jsonl.gz:
```
{"id": "common_voice_en_17299812", "recording_id": "common_voice_en_17299812", "start": 0.0, "duration": 3.432, "channel": 0, "text": "But what is the use of talking?", "language": "en", "speaker": "12ec74c747b4e34f033ebe786f0a74b8af93521aa8f23bc4a83eff4cf64a5c6ac416cdcbdea9ddf5f6c0483ae64a4964060285bcb28d16c609cf5c0bdb484716", "gender": NaN, "custom": {"age": NaN, "accents": NaN}}
{"id": "common_voice_en_17299813", "recording_id": "common_voice_en_17299813", "start": 0.0, "duration": 4.896, "channel": 0, "text": "To calibrate the motion capturing system, please do a T-pose.", "language": "en", "speaker": "12ec74c747b4e34f033ebe786f0a74b8af93521aa8f23bc4a83eff4cf64a5c6ac416cdcbdea9ddf5f6c0483ae64a4964060285bcb28d16c609cf5c0bdb484716", "gender": NaN, "custom": {"age": NaN, "accents": NaN}}
{"id": "common_voice_en_175501", "recording_id": "common_voice_en_175501", "start": 0.0, "duration": 7.632, "channel": 0, "text": "People watching a low airplane flying overhead", "language": "en", "speaker": "12f8304f29c38d2cb6b40c97874623e440985b9405a2720ab2afbc548b5e85a642f05f719e978d450ddfc57a8a380da8114369d5ec9069c7575d8b7d00c534fc", "gender": NaN, "custom": {"age": NaN, "accents": NaN}}
{"id": "common_voice_en_175502", "recording_id": "common_voice_en_175502", "start": 0.0, "duration": 5.448, "channel": 0, "text": "A sleeping toddler has toppled out of his crib", "language": "en", "speaker": "12f8304f29c38d2cb6b40c97874623e440985b9405a2720ab2afbc548b5e85a642f05f719e978d450ddfc57a8a380da8114369d5ec9069c7575d8b7d00c534fc", "gender": NaN, "custom": {"age": NaN, "accents": NaN}}
{"id": "common_voice_en_175503", "recording_id": "common_voice_en_175503", "start": 0.0, "duration": 3.96, "channel": 0, "text": "A night photo of a person making a fireball", "language": "en", "speaker": "12f8304f29c38d2cb6b40c97874623e440985b9405a2720ab2afbc548b5e85a642f05f719e978d450ddfc57a8a380da8114369d5ec9069c7575d8b7d00c534fc", "gender": NaN, "custom": {"age": NaN, "accents": NaN}}
{"id": "common_voice_en_489281", "recording_id": "common_voice_en_489281", "start": 0.0, "duration": 5.016, "channel": 0, "text": "Flowers? Or another magazine subscription?", "language": "en", "speaker": "13102f69d950816ec6a4493b12707afbfaebd315ae5185f0a8d57e0b1c4d65b7b229802ab25c201027b85a2c0c6c2f8c81cab07d413bb2a5db963300c9ae4620", "gender": NaN, "custom": {"age": NaN, "accents": NaN}}
```

It look like there is problem with NaN value since NaN is not supported in JSON
After investigating common voice recipe, I found the problem is that lhotse currently checking pandas columns of "age", "accents"... as string `"nan"` for empty/unknown cell value. E.g. https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/commonvoice.py#L273
But pandas actually using `NaN` (float) value for empty cell:
```
>>> import pandas as pd
>>> df=pd.read_csv("dev.tsv", sep="\t")
>>> id, row=next(df.iterrows())
>>> 
>>> row
client_id     12ec74c747b4e34f033ebe786f0a74b8af93521aa8f23b...
path                               common_voice_en_17299812.mp3
sentence                        But what is the use of talking?
up_votes                                                      2
down_votes                                                    1
age                                                         NaN
gender                                                      NaN
accents                                                     NaN
locale                                                       en
segment                                                     NaN
Name: 0, dtype: object
>>> row.accents
nan
>>> type(row.accents)
<class 'float'>
>>> 

```

Maybe some Common Voice's format change?
And why is it able to write jsonl but unable to load jsonl?

**Comment by pzelasko** [comment]
I think it would be enough if you can add the following line before the dataframe is read: `df[["gender", "age", "accents"]] = df[["gender", "age", "accents"]].fillna("nan")`. Could you make a PR?

**Comment by trunglebka** [comment]
To make it agnostic, I'm planning to code it like this:
```
def parse_utterance(
    row: Any, lang_path: Path, language: str
) -> Tuple[Recording, SupervisionSegment]:
    def read_cv_optional_field(fieldname: str):
        # defaulting instead of raise exception
        if fieldname not in row:
            return None
        cell_val = row[fieldname]
        if cell_val == "nan" or (
            isinstance(cell_val, numbers.Number) and math.isnan(cell_val)
        ):
            return None
        else:
            return cell_val

    # Create the Recording first
    audio_path = lang_path / "clips" / row.path
    if not audio_path.is_file():
        raise ValueError(f"No such file: {audio_path}")
    recording_id = Path(row.path).stem
    recording = Recording.from_file(audio_path, recording_id=recording_id)
    # Handling accent(s) in different versions of CommonVoice
    if "accents" in row:
        accents = read_cv_optional_field("accents")
    else:
        accents = read_cv_optional_field("accent")
```
is it ok?

**Comment by pzelasko** [comment]
Looks good to me, if you're getting the desired results with it, let's merge it
