### ISSUE TITLE
orjson serialization and ensure_ascii=False

### ISSUE THREAD

**Issue by AdolfVonKleist** [lhotse-speech/lhotse#993]
I have a dataset in a non-latin alphabet.  I store this during serialization with `ensure_ascii=False`, mainly for preservation of some human readability.

I noticed that when I try to apply the `compute_fbank_*` step for my dataset that it triggers a `UnicodeDecodeError` which traces back to here:

 * https://github.com/lhotse-speech/lhotse/blob/master/lhotse/serialization.py#L134

I've never had any issue with the standard `json` library for this, but it looks like I have the `orjson` dependency installed, and it is triggering this exception.  I modified this bit to force the use of the standard json library and the error disappeared:

 * https://github.com/lhotse-speech/lhotse/blob/master/lhotse/serialization.py#L600

I don't know if this is a desired behavior or not, seemed worth noting just in case.

**Comment by pzelasko** [comment]
This is surprising, I expected orjson to work correctly with that. Maybe your file is encoded as something different than utf-8. If you had some time to figure this out, it might help future users. A quick fix alternative seems to be uninstalling orjson.

**Comment by AdolfVonKleist** [comment]
@pzelasko yes, you're right, there is a check in the source for whether or not orjson is installed.  I'll double check that all the content is really in utf-8; I didn't consider this because the error was the old 'ascii codec cannot decode...' and switching back to the plain `json` module magically made the issue disappear.  But you are right, it is possible there are some errant invalid content in my corpus; worth double checking this in any case.

**Comment by lifeiteng** [comment]
@AdolfVonKleist  How did you fix this? I have the same problem.

```
  File "/home/feiteng/Geek/OpenSource/speech/k2-fsa/lhotse/lhotse/utils.py", line 867, in streaming_shuffle
    for sample in data:
  File "/home/feiteng/Geek/OpenSource/speech/k2-fsa/lhotse/lhotse/lazy.py", line 165, in values
    yield from self
  File "/home/feiteng/Geek/OpenSource/speech/k2-fsa/lhotse/lhotse/lazy.py", line 165, in values
    yield from self
  File "/home/feiteng/Geek/OpenSource/speech/k2-fsa/lhotse/lhotse/lazy.py", line 216, in __iter__
    yield from map(deserialize_item, self.source)
  File "/home/feiteng/Geek/OpenSource/speech/k2-fsa/lhotse/lhotse/lazy.py", line 186, in __iter__
    for line in f:
  File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc9 in position 613: ordinal not in range(128)
```

**Comment by lifeiteng** [comment]
fixed by using `smart_open`

```
pip install smart_open

def open_best(path: Pathlike, mode: str = "r"):
    """
    Auto-determine the best way to open the input path or URI.
    Uses ``smart_open`` when available to handle URLs and URIs.

    Supports providing "-" as input to read from stdin or save to stdout.

    If the input is prefixed with "pipe:", it will open a subprocess and redirect
    either stdin or stdout depending on the mode.
    The concept is similar to Kaldi's "generalized pipes", but uses WebDataset syntax.
    """
    if str(path) == "-":
        if mode == "r":
            return StdStreamWrapper(sys.stdin)
        elif mode == "w":
            return StdStreamWrapper(sys.stdout)
        else:
            raise ValueError(
                f"Cannot open stream for '-' with mode other 'r' or 'w' (got: '{mode}')"
            )

    if isinstance(path, (BytesIO, StringIO, StreamWriter, StreamReader)):
        return path

    if str(path).startswith("pipe:"):
        return open_pipe(path[5:], mode)

    if is_module_available("smart_open"):
        from smart_open import smart_open

        # This will work with JSONL anywhere that smart_open supports, e.g. cloud storage.
        open_fn = smart_open
    else:
        compressed = str(path).endswith(".gz")
        if compressed and "t" not in mode and "b" not in mode:
            # Opening as bytes not requested explicitly, use "t" to tell gzip to handle unicode.
            mode = mode + "t"
        open_fn = gzip_open_robust if compressed else open

    return open_fn(path, mode)
``` 

It only occurs in new added model, very weird.

**Comment by AdolfVonKleist** [comment]
@lifeiteng I found this issue to be inconsistently reproducible; I'm inclined to agree with @pzelasko that it relates somehow to the locale configured on the machine.  I also noted like you that it seems to only raise its head on 'new' datasets.  I'm not entirely satisified with that as a resolution but I did not end up having trouble getting the training process to work downstream so I guess I will close this for now; someone can reopen later if they encounter the same again.

**Comment by iggygeek** [comment]
I had the same problem. The locale seems to be in UTF-8 so I don't understand.

**Comment by nukes** [comment]
the same problem...  pip install smart_open does not work for me.
<img width="1237" alt="image" src="https://github.com/lhotse-speech/lhotse/assets/4599114/4098a0fc-1b01-4bdd-8f88-19a82eaa6a82">

**Comment by nukes** [comment]
> the same problem... pip install smart_open does not work for me. <img alt="image" width="1237" src="https://private-user-images.githubusercontent.com/4599114/296762576-4098a0fc-1b01-4bdd-8f88-19a82eaa6a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjQxMDAsIm5iZiI6MTcwNTMyMzgwMCwicGF0aCI6Ii80NTk5MTE0LzI5Njc2MjU3Ni00MDk4YTBmYy0xYjAxLTRiZGQtOGY4OC0xOWE4MmVhYTZhODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTMwMzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FjYzZjYmYzZjM0MTNmZTY3M2E5NGZlNmRmNjBiNGQ0NGVjYWM1NWQ0NWNlNzczYzg5NjdjOWJiNjYzM2FjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4sm58XN9r8zcr5hJc33-LIWWKAeIHS8tNS5IqFOxm8w">

it seems like using the ascii decoding, which should not be right.

**Comment by pzelasko** [comment]
Try to re run with the following env var `export LANG=C.UTF8`

**Comment by nukes** [comment]
> Try to re run with the following env var `export LANG=C.UTF8`

I tried, but still did not work. 
This error occurs when i want to load cuts from file:
```python
 print(f"locale is {locale.getdefaultlocale()}")
 print(f"sys default encoding is:{sys.getdefaultencoding()}")
 cut_set = CutSet.from_file(cut_file)
```
```bash
locale is ('en_US', 'UTF-8')
sys default encoding is:utf-8
Traceback (most recent call last):
  File "/data1/martinzheng/tts/backend/larkaudio/examples/codec/train.py", line 29, in <module>
    cli = MyLightningCLI(run=True,parser_kwargs={"parser_mode": "omegaconf"})
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 353, in __init__
    self._run_subcommand(self.subcommand)
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/cli.py", line 642, in _run_subcommand
    fn(**fn_kwargs)
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1014, in _run_stage
    self._run_sanity_check()
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1043, in _run_sanity_check
    val_loop.run()
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 177, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 98, in run
    self.setup_data()
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 150, in setup_data
    dataloaders = _request_dataloader(source)
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 330, in _request_dataloader
    return data_source.dataloader()
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 300, in dataloader
    return call._call_lightning_datamodule_hook(self.instance.trainer, self.name)
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 164, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/data1/martinzheng/tts/backend/larkaudio/larkaudio/datasets/codec_dataset.py", line 77, in val_dataloader
    return self._get_dataloder(self.val_config, train=False)
  File "/data1/martinzheng/tts/backend/larkaudio/larkaudio/datasets/codec_dataset.py", line 63, in _get_dataloder
    dataset = CodecDataset(cfg, train=train)
  File "/data1/martinzheng/tts/backend/larkaudio/larkaudio/datasets/codec_dataset.py", line 105, in __init__
    cut_set = CutSet.from_file(cut_file)
  File "/data1/martinzheng/tts/backend/lhotse/lhotse/serialization.py", line 529, in from_file
    return load_manifest_lazy_or_eager(path, manifest_cls=cls)
  File "/data1/martinzheng/tts/backend/lhotse/lhotse/serialization.py", line 481, in load_manifest_lazy_or_eager
    return load_manifest_lazy(path)
  File "/data1/martinzheng/tts/backend/lhotse/lhotse/serialization.py", line 465, in load_manifest_lazy
    first = next(raw_data)
  File "/data1/martinzheng/tts/backend/lhotse/lhotse/serialization.py", line 132, in load_jsonl
    for line in f:
  File "/data1/martinzheng/miniconda3/envs/py3.10/lib/python3.10/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 18: ordinal not in range(128)
```
i guess this should be introduced by some other library who changed the default encoding when open files. and lhotse does not explicitly setting the encoding to utf-8 when open *.jsonl.gz file

**Comment by nukes** [comment]
i changed some code in lhotse: use utf-8 encoding for open with text mode:
<img width="832" alt="image" src="https://github.com/lhotse-speech/lhotse/assets/4599114/be26904c-c6f7-46b1-abba-3f4ebe4f4d94">

This is a workaround for me.

**Comment by pzelasko** [comment]
I would be OK to add an env var support in Lhotse e.g. `LHOTSE_FORCE_ENCODING=<value>` to override the default settings (I don't think that introducing arguments in all manifest opening functions is practical). However I'm still unsure why do you need it or which specific setting differs between your and others' systems that causes this behavior.
